SELECT * FROM DimProduct

----------------------------------------------------------------------------------------------------------------------------------First batch
INSERT INTO dbo.DimProduct(ProductKey,ProductName,ProductCategory)
VALUES (1000,'<"While you Were Out" Message Book, One Form per Page>','Paper'),
(1001,'<#10- 4 1/8" x 9 1/2" Recycled Envelopes>','Envelopes'),
(1002,'<#10- 4 1/8" x 9 1/2" Security-Tint Envelopes>','Envelopes'),
(1003,'<#10 Self-Seal White Envelopes>','Envelopes'),
(1004,'<#10 White Business Envelopes,4 1/8 x 9 1/2>','Envelopes'),
(1005,'<#6 3/4 Gummed Flap White Envelopes>','Envelopes'),
(1006,'<12 Colored Short Pencils>','Art'),
(1007,'<12-1/2 Diameter Round Wall Clock>','Furnishings'),
(1008,'<14-7/8 x 11 Blue Bar Computer Printout Paper>','Paper'),
(1009,'<2300 Heavy-Duty Transfer File Systems by Perma>','Storage'),
(1010,'<24 Capacity Maxi Data Binder Racks, Pearl>','Storage'),
(1011,'<24-Hour Round Wall Clock>','Furnishings'),
(1012,'<3.6 Cubic Foot Counter Height Office Refrigerator>','Appliances'),
(1013,'<36X48 HARDFLOOR CHAIRMAT>','Furnishings'),
(1014,'<3D Systems Cube Printer, 2nd Generation, White>','Machines'),
(1015,'<3M Hangers With Command Adhesive>','Furnishings'),
(1016,'<3M Office Air Cleaner>','Appliances'),
(1017,'<3M Polarizing Light Filter Sleeves>','Furnishings'),
(1018,'<3M Replacement Filter for Office Air Cleaner for 20'' x 33'' Room>','Appliances'),
(1019,'<4009 Highlighters by Sanford>','Art'),
(1020,'<50 Colored Long Pencils>','Art'),
(1021,'<6" Cubicle Wall Clock, Black>','Furnishings'),
(1022,'<9-3/4 Diameter Round Wall Clock>','Furnishings'),
(1023,'<Aastra 57i VoIP phone>','Phones'),
(1024,'<Aastra 6757i CT Wireless VoIP phone>','Phones'),
(1025,'<Acco 3-Hole Punch>','Binders'),
(1026,'<Acco 6 Outlet Guardian Premium Plus Surge Suppressor>','Appliances'),
(1027,'<Acco 6 Outlet Guardian Premium Surge Suppressor>','Appliances'),
(1028,'<Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection>','Appliances'),
(1029,'<Acco Banker''s Clasps, 5 3/4"-Long>','Fasteners'),
(1030,'<Acco Clips to Go Binder Clips, 24 Clips in Two Sizes>','Fasteners'),
(1031,'<Acco Data Flex Cable Posts For Top & Bottom Load Binders, 6" Capacity>','Binders'),
(1032,'<Acco D-Ring Binder w/DublLock>','Binders'),
(1033,'<Acco Economy Flexible Poly Round Ring Binder>','Binders'),
(1034,'<Acco Expandable Hanging Binders>','Binders'),
(1035,'<Acco Flexible ACCOHIDE Square Ring Data Binder, Dark Blue, 11 1/2" X 14" 7/8">','Binders'),
(1036,'<Acco Four Pocket Poly Ring Binder with Label Holder, Smoke, 1">','Binders'),
(1037,'<Acco Glide Clips>','Fasteners'),
(1038,'<Acco Hanging Data Binders>','Binders'),
(1039,'<Acco Perma 2700 Stacking Storage Drawers>','Storage'),
(1040,'<Acco Perma 3000 Stacking Storage Drawers>','Storage'),
(1041,'<Acco Perma 4000 Stacking Storage Drawers>','Storage'),
(1042,'<Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Dark Blue>','Binders'),
(1043,'<Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Executive Red>','Binders'),
(1044,'<Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Light Blue>','Binders'),
(1045,'<Acco Pressboard Covers with Storage Hooks, 9 1/2" x 11", Executive Red>','Binders'),
(1046,'<Acco PRESSTEX Data Binder with Storage Hooks, Dark Blue, 14 7/8" X 11">','Binders'),
(1047,'<Acco PRESSTEX Data Binder with Storage Hooks, Dark Blue, 9 1/2" X 11">','Binders'),
(1048,'<Acco PRESSTEX Data Binder with Storage Hooks, Light Blue, 9 1/2" X 11">','Binders'),
(1049,'<Acco Recycled 2" Capacity Laser Printer Hanging Data Binders>','Binders'),
(1050,'<Acco Side-Punched Conventional Columnar Pads>','Supplies'),
(1051,'<Acco Six-Outlet Power Strip, 4'' Cord Length>','Appliances'),
(1052,'<Acco Smartsocket Color-Coded Six-Outlet AC Adapter Model Surge Protectors>','Appliances'),
(1053,'<Acco Smartsocket Table Surge Protector, 6 Color-Coded Adapter Outlets>','Appliances'),
(1054,'<Acco Suede Grain Vinyl Round Ring Binder>','Binders'),
(1055,'<Acco Translucent Poly Ring Binders>','Binders'),
(1056,'<ACCOHIDE 3-Ring Binder, Blue, 1">','Binders'),
(1057,'<ACCOHIDE Binder by Acco>','Binders'),
(1058,'<Accohide Poly Flexible Ring Binders>','Binders'),
(1059,'<Acme 10" Easy Grip Assistive Scissors>','Supplies'),
(1060,'<Acme Box Cutter Scissors>','Supplies'),
(1061,'<Acme Design Line 8" Stainless Steel Bent Scissors w/Champagne Handles, 3-1/8" Cut>','Supplies'),
(1062,'<Acme Design Stainless Steel Bent Scissors>','Supplies'),
(1063,'<Acme Elite Stainless Steel Scissors>','Supplies'),
(1064,'<Acme Forged Steel Scissors with Black Enamel Handles>','Supplies'),
(1065,'<Acme Galleria Hot Forged Steel Scissors with Colored Handles>','Supplies'),
(1066,'<Acme Hot Forged Carbon Steel Scissors with Nickel-Plated Handles, 3 7/8" Cut, 8"L>','Supplies'),
(1067,'<Acme Kleen Earth Office Shears>','Supplies'),
(1068,'<Acme Kleencut Forged Steel Scissors>','Supplies'),
(1069,'<Acme Office Executive Series Stainless Steel Trimmers>','Supplies'),
(1070,'<Acme Preferred Stainless Steel Scissors>','Supplies'),
(1071,'<Acme Rosewood Handle Letter Opener>','Supplies'),
(1072,'<Acme Softgrip Scissors>','Supplies'),
(1073,'<Acme Tagit Stainless Steel Antibacterial Scissors>','Supplies'),
(1074,'<Acme Titanium Bonded Scissors>','Supplies'),
(1075,'<Acme Value Line Scissors>','Supplies'),
(1076,'<Acrylic Self-Standing Desk Frames>','Furnishings'),
(1077,'<Adams "While You Were Out" Message Pads>','Paper'),
(1078,'<Adams Phone Message Book, 200 Message Capacity, 8 1/16” x 11”>','Paper'),
(1079,'<Adams Phone Message Book, Professional, 400 Message Capacity, 5 3/6” x 11”>','Paper'),
(1080,'<Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4"X8 1/2", 200/Messages>','Paper'),
(1081,'<Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4"X8 1/2", 300/Messages>','Paper'),
(1082,'<Adams Telephone Message Book w/Frequently-Called Numbers Space, 400 Messages per Book>','Paper'),
(1083,'<Adjustable Depth Letter/Legal Cart>','Storage'),
(1084,'<Adjustable Personal File Tote>','Storage'),
(1085,'<Adtran 1202752G1>','Phones'),
(1086,'<Advantus Employee of the Month Certificate Frame, 11 x 13-1/2>','Furnishings'),
(1087,'<Advantus Map Pennant Flags and Round Head Tacks>','Fasteners'),
(1088,'<Advantus Panel Wall Acrylic Frame>','Furnishings'),
(1089,'<Advantus Panel Wall Certificate Holder - 8.5x11>','Furnishings'),
(1090,'<Advantus Plastic Paper Clips>','Fasteners'),
(1091,'<Advantus Push Pins>','Fasteners'),
(1092,'<Advantus Push Pins, Aluminum Head>','Fasteners'),
(1093,'<Advantus Rolling Drawer Organizers>','Storage'),
(1094,'<Advantus Rolling Storage Box>','Storage'),
(1095,'<Advantus SlideClip Paper Clips>','Fasteners'),
(1096,'<Advantus T-Pin Paper Clips>','Fasteners'),
(1097,'<Airmail Envelopes>','Envelopes'),
(1098,'<Akro Stacking Bins>','Storage'),
(1099,'<Akro-Mils 12-Gallon Tote>','Storage'),
(1100,'<Alliance Big Bands Rubber Bands, 12/Pack>','Fasteners'),
(1101,'<Alliance Rubber Bands>','Fasteners'),
(1102,'<Alliance Super-Size Bands, Assorted Sizes>','Fasteners'),
(1103,'<Alphabetical Labels for Top Tab Filing>','Labels'),
(1104,'<Aluminum Document Frame>','Furnishings'),
(1105,'<Aluminum Screw Posts>','Binders'),
(1106,'<AmazonBasics 3-Button USB Wired Mouse>','Accessories'),
(1107,'<American Pencil>','Art'),
(1108,'<Ames Color-File Green Diamond Border X-ray Mailers>','Envelopes'),
(1109,'<Ampad #10 Peel & Seel Holiday Envelopes>','Envelopes'),
(1110,'<Ampad Evidence Wirebond Steno Books, 6" x 9">','Paper'),
(1111,'<Ampad Gold Fibre Wirebound Steno Books, 6" x 9", Gregg Ruled>','Paper'),
(1112,'<Ampad Phone Message Book, Recycled, 400 Message Capacity, 5 ¾” x 11”>','Paper'),
(1113,'<Anderson Hickey Conga Table Tops & Accessories>','Tables'),
(1114,'<Angle-D Binders with Locking Rings, Label Holders>','Binders'),
(1115,'<Anker 24W Portable Micro USB Car Charger>','Phones'),
(1116,'<Anker 36W 4-Port USB Wall Charger Travel Power Adapter for iPhone 5s 5c 5>','Phones'),
(1117,'<Anker Astro 15000mAh USB Portable Charger>','Phones'),
(1118,'<Anker Astro Mini 3000mAh Ultra-Compact Portable Charger>','Phones'),
(1119,'<Anker Ultra-Slim Mini Bluetooth 3.0 Wireless Keyboard>','Accessories'),
(1120,'<APC 7 Outlet Network SurgeArrest Surge Protector>','Appliances'),
(1121,'<Apple iPhone 5>','Phones'),
(1122,'<Apple iPhone 5S>','Phones'),
(1123,'<Array Memo Cubes>','Paper'),
(1124,'<Assorted Color Push Pins>','Fasteners'),
(1125,'<Astroparche Fine Business Paper>','Paper'),
(1126,'<AT&T 1070 Corded Phone>','Phones'),
(1127,'<AT&T 1080 Corded phone>','Phones'),
(1128,'<AT&T 1080 Phone>','Phones'),
(1129,'<AT&T 17929 Lendline Telephone>','Phones'),
(1130,'<AT&T 841000 Phone>','Phones'),
(1131,'<AT&T CL2909>','Phones'),
(1132,'<AT&T CL82213>','Phones'),
(1133,'<AT&T CL83451 4-Handset Telephone>','Phones'),
(1134,'<AT&T SB67148 SynJ>','Phones'),
(1135,'<AT&T TR1909W>','Phones'),
(1136,'<Ativa MDM8000 8-Sheet Micro-Cut Shredder>','Machines'),
(1137,'<Atlantic Metals Mobile 2-Shelf Bookcases, Custom Colors>','Bookcases'),
(1138,'<Atlantic Metals Mobile 3-Shelf Bookcases, Custom Colors>','Bookcases'),
(1139,'<Atlantic Metals Mobile 4-Shelf Bookcases, Custom Colors>','Bookcases'),
(1140,'<Atlantic Metals Mobile 5-Shelf Bookcases, Custom Colors>','Bookcases'),
(1141,'<Avanti 4.4 Cu. Ft. Refrigerator>','Appliances'),
(1142,'<Avaya 4621SW VoIP phone>','Phones'),
(1143,'<Avaya 5410 Digital phone>','Phones'),
(1144,'<Avery 3 1/2" Diskette Storage Pages, 10/Pack>','Binders'),
(1145,'<Avery 4027 File Folder Labels for Dot Matrix Printers, 5000 Labels per Box, White>','Labels'),
(1146,'<Avery 473>','Labels'),
(1147,'<Avery 474>','Labels'),
(1148,'<Avery 475>','Labels'),
(1149,'<Avery 476>','Labels'),
(1150,'<Avery 477>','Labels'),
(1151,'<Avery 478>','Labels'),
(1152,'<Avery 48>','Labels'),
(1153,'<Avery 480>','Labels'),
(1154,'<Avery 481>','Labels'),
(1155,'<Avery 482>','Labels'),
(1156,'<Avery 483>','Labels'),
(1157,'<Avery 485>','Labels'),
(1158,'<Avery 486>','Labels'),
(1159,'<Avery 487>','Labels'),
(1160,'<Avery 488>','Labels'),
(1161,'<Avery 489>','Labels'),
(1162,'<Avery 49>','Labels'),
(1163,'<Avery 490>','Labels'),
(1164,'<Avery 492>','Labels'),
(1165,'<Avery 493>','Labels'),
(1166,'<Avery 494>','Labels'),
(1167,'<Avery 495>','Labels'),
(1168,'<Avery 496>','Labels'),
(1169,'<Avery 497>','Labels'),
(1170,'<Avery 498>','Labels'),
(1171,'<Avery 499>','Labels'),
(1172,'<Avery 50>','Labels'),
(1173,'<Avery 500>','Labels'),
(1174,'<Avery 501>','Labels'),
(1175,'<Avery 503>','Labels'),
(1176,'<Avery 505>','Labels'),
(1177,'<Avery 506>','Labels'),
(1178,'<Avery 507>','Labels'),
(1179,'<Avery 508>','Labels'),
(1180,'<Avery 509>','Labels'),
(1181,'<Avery 51>','Labels'),
(1182,'<Avery 510>','Labels'),
(1183,'<Avery 511>','Labels'),
(1184,'<Avery 512>','Labels'),
(1185,'<Avery 513>','Labels'),
(1186,'<Avery 514>','Labels'),
(1187,'<Avery 516>','Labels'),
(1188,'<Avery 517>','Labels'),
(1189,'<Avery 518>','Labels'),
(1190,'<Avery 519>','Labels'),
(1191,'<Avery 52>','Labels'),
(1192,'<Avery Address/Shipping Labels for Typewriters, 4" x 2">','Labels'),
(1193,'<Avery Arch Ring Binders>','Binders'),
(1194,'<Avery Binder Labels>','Binders'),
(1195,'<Avery Binding System Hidden Tab Executive Style Index Sets>','Binders'),
(1196,'<Avery Durable Binders>','Binders'),
(1197,'<Avery Durable Plastic 1" Binders>','Binders'),
(1198,'<Avery Durable Poly Binders>','Binders'),
(1199,'<Avery Durable Slant Ring Binders>','Binders'),
(1200,'<Avery Durable Slant Ring Binders With Label Holder>','Binders'),
(1201,'<Avery Durable Slant Ring Binders, No Labels>','Binders'),
(1202,'<Avery File Folder Labels>','Labels'),
(1203,'<Avery Framed View Binder, EZD Ring (Locking), Navy, 1 1/2">','Binders'),
(1204,'<Avery Hanging File Binders>','Binders'),
(1205,'<Avery Heavy-Duty EZD  Binder With Locking Rings>','Binders'),
(1206,'<Avery Heavy-Duty EZD View Binder with Locking Rings>','Binders'),
(1207,'<Avery Hidden Tab Dividers for Binding Systems>','Binders'),
(1208,'<Avery Hi-Liter EverBold Pen Style Fluorescent Highlighters, 4/Pack>','Art'),
(1209,'<Avery Hi-Liter Fluorescent Desk Style Markers>','Art'),
(1210,'<Avery Hi-Liter Smear-Safe Highlighters>','Art'),
(1211,'<Avery Hole Reinforcements>','Binders'),
(1212,'<Avery Legal 4-Ring Binder>','Binders'),
(1213,'<Avery Metallic Poly Binders>','Binders'),
(1214,'<Avery Non-Stick Binders>','Binders'),
(1215,'<Avery Non-Stick Heavy Duty View Round Locking Ring Binders>','Binders'),
(1216,'<Avery Personal Creations Heavyweight Cards>','Paper'),
(1217,'<Avery Poly Binder Pockets>','Binders'),
(1218,'<Avery Premier Heavy-Duty Binder with Round Locking Rings>','Binders'),
(1219,'<Avery Printable Repositionable Plastic Tabs>','Binders'),
(1220,'<Avery Reinforcements for Hole-Punch Pages>','Binders'),
(1221,'<Avery Round Ring Poly Binders>','Binders'),
(1222,'<Avery Self-Adhesive Photo Pockets for Polaroid Photos>','Binders'),
(1223,'<Avery Trapezoid Extra Heavy Duty 4" Binders>','Binders'),
(1224,'<Avery Trapezoid Ring Binder, 3" Capacity, Black, 1040 sheets>','Binders'),
(1225,'<Avery White Multi-Purpose Labels>','Labels'),
(1226,'<Bady BDG101FRU Card Printer>','Machines'),
(1227,'<Bagged Rubber Bands>','Fasteners'),
(1228,'<Balt Solid Wood Rectangular Table>','Tables'),
(1229,'<Balt Solid Wood Round Tables>','Tables'),
(1230,'<Balt Split Level Computer Training Table>','Tables'),
(1231,'<Barricks 18" x 48" Non-Folding Utility Table with Bottom Storage Shelf>','Tables'),
(1232,'<Barricks Non-Folding Utility Table with Steel Legs, Laminate Tops>','Tables'),
(1233,'<Belkin 19" Center-Weighted Shelf, Gray>','Storage'),
(1234,'<Belkin 19" Vented Equipment Shelf, Black>','Storage'),
(1235,'<Belkin 325VA UPS Surge Protector, 6''>','Appliances'),
(1236,'<Belkin 5 Outlet SurgeMaster Power Centers>','Appliances'),
(1237,'<Belkin 6 Outlet Metallic Surge Strip>','Appliances'),
(1238,'<Belkin 7 Outlet SurgeMaster II>','Appliances'),
(1239,'<Belkin 7 Outlet SurgeMaster Surge Protector with Phone Protection>','Appliances'),
(1240,'<Belkin 7-Outlet SurgeMaster Home Series>','Appliances'),
(1241,'<Belkin 8 Outlet Surge Protector>','Appliances'),
(1242,'<Belkin 8 Outlet SurgeMaster II Gold Surge Protector>','Appliances'),
(1243,'<Belkin 8-Outlet Premiere SurgeMaster II Surge Protectors>','Appliances'),
(1244,'<Belkin F5C206VTEL 6 Outlet Surge>','Appliances'),
(1245,'<Belkin F8E887 USB Wired Ergonomic Keyboard>','Accessories'),
(1246,'<Belkin F9G930V10-GRY 9 Outlet Surge>','Appliances'),
(1247,'<Belkin F9H710-06 7 Outlet SurgeMaster Surge Protector>','Appliances'),
(1248,'<Belkin F9S820V06 8 Outlet Surge>','Appliances'),
(1249,'<Belkin iPhone and iPad Lightning Cable>','Phones'),
(1250,'<Belkin Premiere Surge Master II 8-outlet surge protector>','Appliances'),
(1251,'<Belkin Standard 104 key USB Keyboard>','Accessories'),
(1252,'<Berol Giant Pencil Sharpener>','Art'),
(1253,'<Bestar Classic Bookcase>','Bookcases'),
(1254,'<Bevis 36 x 72 Conference Tables>','Tables'),
(1255,'<Bevis Boat-Shaped Conference Table>','Tables'),
(1256,'<Bevis Oval Conference Table, Walnut>','Tables'),
(1257,'<Bevis Rectangular Conference Tables>','Tables'),
(1258,'<Bevis Round Bullnose 29" High Table Top>','Tables'),
(1259,'<Bevis Round Conference Room Tables and Bases>','Tables'),
(1260,'<Bevis Round Conference Table Top & Single Column Base>','Tables'),
(1261,'<Bevis Round Conference Table Top, X-Base>','Tables'),
(1262,'<Bevis Steel Folding Chairs>','Chairs'),
(1263,'<BIC Brite Liner Grip Highlighters, Assorted, 5/Pack>','Art'),
(1264,'<BIC Brite Liner Highlighters>','Art'),
(1265,'<BIC Brite Liner Highlighters, Chisel Tip>','Art'),
(1266,'<BIC Liqua Brite Liner>','Art'),
(1267,'<Binder Clips by OIC>','Fasteners'),
(1268,'<Binder Posts>','Binders'),
(1269,'<Binding Machine Supplies>','Binders'),
(1270,'<Binney & Smith Crayola Metallic Colored Pencils, 8-Color Set>','Art'),
(1271,'<Binney & Smith Crayola Metallic Crayons, 16-Color Pack>','Art'),
(1272,'<Binney & Smith inkTank Desk Highlighter, Chisel Tip, Yellow, 12/Box>','Art'),
(1273,'<Bionaire Personal Warm Mist Humidifier/Vaporizer>','Appliances'),
(1274,'<Black Avery Memo-Size 3-Ring Binder, 5 1/2" x 8 1/2">','Binders'),
(1275,'<Black Print Carbonless 8 1/2" x 8 1/4" Rapid Memo Book>','Paper'),
(1276,'<Black Print Carbonless Snap-Off Rapid Letter, 8 1/2" x 7">','Paper'),
(1277,'<BlackBerry Q10>','Phones'),
(1278,'<Blackstonian Pencils>','Art'),
(1279,'<Blue Parrot B250XT Professional Grade Wireless Bluetooth Headset with>','Phones'),
(1280,'<Bose SoundLink Bluetooth Speaker>','Phones'),
(1281,'<Boston 16701 Slimline Battery Pencil Sharpener>','Art'),
(1282,'<Boston 16765 Mini Stand Up Battery Pencil Sharpener>','Art'),
(1283,'<Boston 16801 Nautilus Battery Pencil Sharpener>','Art'),
(1284,'<Boston 1730 StandUp Electric Pencil Sharpener>','Art'),
(1285,'<Boston 1799 Powerhouse Electric Pencil Sharpener>','Art'),
(1286,'<Boston 1827 Commercial Additional Cutter, Drive Gear & Gear Rack for 1606>','Art'),
(1287,'<Boston 19500 Mighty Mite Electric Pencil Sharpener>','Art'),
(1288,'<Boston Electric Pencil Sharpener, Model 1818, Charcoal Black>','Art'),
(1289,'<Boston Heavy-Duty Trimline Electric Pencil Sharpeners>','Art'),
(1290,'<Boston Home & Office Model 2000 Electric Pencil Sharpeners>','Art'),
(1291,'<Boston KS Multi-Size Manual Pencil Sharpener>','Art'),
(1292,'<BOSTON Model 1800 Electric Pencil Sharpeners, Putty/Woodgrain>','Art'),
(1293,'<BOSTON Ranger #55 Pencil Sharpener, Black>','Art'),
(1294,'<Boston School Pro Electric Pencil Sharpener, 1670>','Art'),
(1295,'<BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables>','Tables'),
(1296,'<Bravo II Megaboss 12-Amp Hard Body Upright, Replacement Belts, 2 Belts per Pack>','Appliances'),
(1297,'<Bretford “Just In Time” Height-Adjustable Multi-Task Work Tables>','Tables'),
(1298,'<Bretford CR4500 Series Slim Rectangular Table>','Tables'),
(1299,'<Bretford CR8500 Series Meeting Room Furniture>','Tables'),
(1300,'<Bretford Rectangular Conference Table Tops>','Tables'),
(1301,'<Brites Rubber Bands, 1 1/2 oz. Box>','Fasteners'),
(1302,'<Brother DCP1000 Digital 3 in 1 Multifunction Machine>','Copiers'),
(1303,'<Bulldog Table or Wall-Mount Pencil Sharpener>','Art'),
(1304,'<Bulldog Vacuum Base Pencil Sharpener>','Art'),
(1305,'<Bush Advantage Collection Racetrack Conference Table>','Tables'),
(1306,'<Bush Advantage Collection Round Conference Table>','Tables'),
(1307,'<Bush Andora Bookcase, Maple/Graphite Gray Finish>','Bookcases'),
(1308,'<Bush Andora Conference Table, Maple/Graphite Gray Finish>','Tables'),
(1309,'<Bush Cubix Collection Bookcases, Fully Assembled>','Bookcases'),
(1310,'<Bush Cubix Conference Tables, Fully Assembled>','Tables'),
(1311,'<Bush Heritage Pine Collection 5-Shelf Bookcase, Albany Pine Finish, *Special Order>','Bookcases'),
(1312,'<Bush Saratoga Collection 5-Shelf Bookcase, Hanover Cherry, *Special Order>','Bookcases'),
(1313,'<Bush Somerset Collection Bookcase>','Bookcases'),
(1314,'<Bush Westfield Collection Bookcases, Dark Cherry Finish>','Bookcases'),
(1315,'<Bush Westfield Collection Bookcases, Dark Cherry Finish, Fully Assembled>','Bookcases'),
(1316,'<Bush Westfield Collection Bookcases, Fully Assembled>','Bookcases'),
(1317,'<Bush Westfield Collection Bookcases, Medium Cherry Finish>','Bookcases'),
(1318,'<Cameo Buff Policy Envelopes>','Envelopes'),
(1319,'<Canon Image Class D660 Copier>','Copiers'),
(1320,'<Canon imageCLASS 2200 Advanced Copier>','Copiers'),
(1321,'<Canon Imageclass D680 Copier / Fax>','Copiers'),
(1322,'<Canon PC1060 Personal Laser Copier>','Copiers'),
(1323,'<Canon PC1080F Personal Copier>','Copiers'),
(1324,'<Canon PC-428 Personal Copier>','Copiers'),
(1325,'<Canon PC940 Copier>','Copiers'),
(1326,'<Canvas Sectional Post Binders>','Binders'),
(1327,'<Cardinal EasyOpen D-Ring Binders>','Binders'),
(1328,'<Cardinal Holdit Business Card Pockets>','Binders'),
(1329,'<Cardinal Hold-It CD Pocket>','Binders'),
(1330,'<Cardinal Holdit Data Disk Pockets>','Binders'),
(1331,'<Cardinal HOLDit! Binder Insert Strips,Extra Strips>','Binders'),
(1332,'<Cardinal Poly Pocket Divider Pockets for Ring Binders>','Binders'),
(1333,'<Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl>','Binders'),
(1334,'<Cardinal Slant-D Ring Binders>','Binders'),
(1335,'<Carina 42"Hx23 3/4"W Media Storage Unit>','Storage'),
(1336,'<Carina Double Wide Media Storage Towers in Natural & Black>','Storage'),
(1337,'<Carina Media Storage Towers in Natural & Black>','Storage'),
(1338,'<Carina Mini System Audio Rack, Model AR050B>','Storage'),
(1339,'<Case Logic 2.4GHz Wireless Keyboard>','Accessories'),
(1340,'<Catalog Binders with Expanding Posts>','Binders'),
(1341,'<Cherry 142-key Programmable Keyboard>','Accessories'),
(1342,'<Chromcraft 48" x 96" Racetrack Double Pedestal Table>','Tables'),
(1343,'<Chromcraft Bull-Nose Wood 48" x 96" Rectangular Conference Tables>','Tables'),
(1344,'<Chromcraft Bull-Nose Wood Oval Conference Tables & Bases>','Tables'),
(1345,'<Chromcraft Bull-Nose Wood Round Conference Table Top, Wood Base>','Tables'),
(1346,'<Chromcraft Rectangular Conference Tables>','Tables'),
(1347,'<Chromcraft Round Conference Tables>','Tables'),
(1348,'<Cisco 8x8 Inc. 6753i IP Business Phone System>','Phones'),
(1349,'<Cisco Desktop Collaboration Experience DX650 IP Video Phone>','Machines'),
(1350,'<Cisco IP Phone 7961G-GE VoIP phone>','Phones'),
(1351,'<Cisco Small Business SPA 502G VoIP phone>','Phones'),
(1352,'<Cisco SPA 501G IP Phone>','Phones'),
(1353,'<Cisco SPA 502G IP Phone>','Phones'),
(1354,'<Cisco SPA301>','Phones'),
(1355,'<Cisco SPA508G>','Phones'),
(1356,'<Cisco SPA525G2 IP Phone - Wireless>','Phones'),
(1357,'<Cisco Unified IP Phone 7945G VoIP phone>','Phones'),
(1358,'<Clarity 53712>','Phones'),
(1359,'<Clear Mylar Reinforcing Strips>','Binders'),
(1360,'<ClearOne CHATAttach 160 - speaker phone>','Phones'),
(1361,'<Clearsounds A400>','Phones'),
(1362,'<ClearSounds CSC500 Amplified Spirit Phone Corded phone>','Phones'),
(1363,'<C-Line Cubicle Keepers Polyproplyene Holder With Velcro Backings>','Furnishings'),
(1364,'<C-Line Magnetic Cubicle Keepers, Clear Polypropylene>','Furnishings'),
(1365,'<C-Line Peel & Stick Add-On Filing Pockets, 8-3/4 x 5-1/8, 10/Pack>','Binders'),
(1366,'<Col-Erase Pencils with Erasers>','Art'),
(1367,'<Colored Push Pins>','Fasteners'),
(1368,'<Coloredge Poster Frame>','Furnishings'),
(1369,'<Commercial WindTunnel Clean Air Upright Vacuum, Replacement Belts, Filtration Bags>','Appliances'),
(1370,'<Compact Automatic Electric Letter Opener>','Supplies'),
(1371,'<Companion Letter/Legal File, Black>','Storage'),
(1372,'<Computer Printout Index Tabs>','Binders'),
(1373,'<Computer Printout Paper with Letter-Trim Perforations>','Paper'),
(1374,'<Computer Room Manger, 14">','Furnishings'),
(1375,'<Conquest 14 Commercial Heavy-Duty Upright Vacuum, Collection System, Accessory Kit>','Appliances'),
(1376,'<Contemporary Borderless Frame>','Furnishings'),
(1377,'<Contemporary Wood/Metal Frame>','Furnishings'),
(1378,'<Contico 72"H Heavy-Duty Storage System>','Storage'),
(1379,'<Contract Clock, 14", Brown>','Furnishings'),
(1380,'<Convenience Packs of Business Envelopes>','Envelopes'),
(1381,'<Crayola Anti Dust Chalk, 12/Pack>','Art'),
(1382,'<Crayola Colored Pencils>','Art'),
(1383,'<Cubify CubeX 3D Printer Double Head Print>','Machines'),
(1384,'<Cush Cases Heavy Duty Rugged Cover Case for Samsung Galaxy S5 - Purple>','Phones'),
(1385,'<Cyber Acoustics AC-202b Speech Recognition Stereo Headset>','Phones'),
(1386,'<Dana Halogen Swing-Arm Architect Lamp>','Furnishings'),
(1387,'<Dana Swing-Arm Lamps>','Furnishings'),
(1388,'<DAX Black Cherry Wood-Tone Poster Frame>','Furnishings'),
(1389,'<DAX Charcoal/Nickel-Tone Document Frame, 5 x 7>','Furnishings'),
(1390,'<Dax Clear Box Frame>','Furnishings'),
(1391,'<DAX Clear Channel Poster Frame>','Furnishings'),
(1392,'<DAX Contemporary Wood Frame with Silver Metal Mat, Desktop, 11 x 14 Size>','Furnishings'),
(1393,'<DAX Copper Panel Document Frame, 5 x 7 Size>','Furnishings'),
(1394,'<DAX Cubicle Frames - 8x10>','Furnishings'),
(1395,'<DAX Cubicle Frames, 8-1/2 x 11>','Furnishings'),
(1396,'<DAX Executive Solid Wood Document Frame, Desktop or Hang, Mahogany, 5 x 7>','Furnishings'),
(1397,'<DAX Metal Frame, Desktop, Stepped-Edge>','Furnishings'),
(1398,'<DAX Natural Wood-Tone Poster Frame>','Furnishings'),
(1399,'<DAX Solid Wood Frames>','Furnishings'),
(1400,'<DAX Two-Tone Rosewood/Black Document Frame, Desktop, 5 x 7>','Furnishings'),
(1401,'<DAX Two-Tone Silver Metal Document Frame>','Furnishings'),
(1402,'<DAX Value U-Channel Document Frames, Easel Back>','Furnishings'),
(1403,'<DAX Wood Document Frame>','Furnishings'),
(1404,'<Decoflex Hanging Personal Folder File, Blue>','Storage'),
(1405,'<Deflect-o DuraMat Antistatic Studded Beveled Mat for Medium Pile Carpeting>','Furnishings'),
(1406,'<Deflect-o DuraMat Lighweight, Studded, Beveled Mat for Low Pile Carpeting>','Furnishings'),
(1407,'<Deflect-o EconoMat Nonstudded, No Bevel Mat>','Furnishings'),
(1408,'<Deflect-o EconoMat Studded, No Bevel Mat for Low Pile Carpeting>','Furnishings'),
(1409,'<Deflect-o Glass Clear Studded Chair Mats>','Furnishings'),
(1410,'<Deflect-O Glasstique Clear Desk Accessories>','Furnishings'),
(1411,'<Deflect-o RollaMat Studded, Beveled Mat for Medium Pile Carpeting>','Furnishings'),
(1412,'<Deflect-o SuperTray Unbreakable Stackable Tray, Letter, Black>','Furnishings'),
(1413,'<Deluxe Chalkboard Eraser Cleaner>','Art'),
(1414,'<Deluxe Heavy-Duty Vinyl Round Ring Binder>','Binders'),
(1415,'<Deluxe Rollaway Locking File with Drawer>','Storage'),
(1416,'<Design Ebony Sketching Pencil>','Art'),
(1417,'<Dexim XPower Skin Super-Thin Power Case for iPhone 5 - Black>','Phones'),
(1418,'<Digium D40 VoIP phone>','Phones'),
(1419,'<Dixon My First Ticonderoga Pencil, #2>','Art'),
(1420,'<DIXON Oriole Pencils>','Art'),
(1421,'<Dixon Prang Watercolor Pencils, 10-Color Set with Brush>','Art'),
(1422,'<Dixon Ticonderoga Core-Lock Colored Pencils>','Art'),
(1423,'<Dixon Ticonderoga Core-Lock Colored Pencils, 48-Color Set>','Art'),
(1424,'<Dixon Ticonderoga Erasable Colored Pencil Set, 12-Color>','Art'),
(1425,'<Dixon Ticonderoga Maple Cedar Pencil, #2>','Art'),
(1426,'<Dixon Ticonderoga Pencils>','Art'),
(1427,'<DMI Arturo Collection Mission-style Design Wood Chair>','Chairs'),
(1428,'<DMI Eclipse Executive Suite Bookcases>','Bookcases'),
(1429,'<Document Clip Frames>','Furnishings'),
(1430,'<Dot Matrix Printer Tape Reel Labels, White, 5000/Box>','Labels'),
(1431,'<Dual Level, Single-Width Filing Carts>','Storage'),
(1432,'<DXL Angle-View Binders with Locking Rings by Samsill>','Binders'),
(1433,'<DXL Angle-View Binders with Locking Rings, Black>','Binders'),
(1434,'<DYMO CardScan Personal V9 Business Card Scanner>','Machines'),
(1435,'<Eaton Premium Continuous-Feed Paper, 25% Cotton, Letter Size, White, 1000 Shts/Box>','Paper'),
(1436,'<Eberhard Faber 3 1/2" Golf Pencils>','Art'),
(1437,'<Economy #2 Pencils>','Art'),
(1438,'<Economy Binders>','Binders'),
(1439,'<Economy Rollaway Files>','Storage'),
(1440,'<EcoTones Memo Sheets>','Paper'),
(1441,'<Eldon "L" Workstation Diamond Chairmat>','Furnishings'),
(1442,'<Eldon 100 Class Desk Accessories>','Furnishings'),
(1443,'<Eldon 200 Class Desk Accessories>','Furnishings'),
(1444,'<Eldon 200 Class Desk Accessories, Burgundy>','Furnishings'),
(1445,'<Eldon 200 Class Desk Accessories, Smoke>','Furnishings'),
(1446,'<Eldon 300 Class Desk Accessories, Black>','Furnishings'),
(1447,'<Eldon 400 Class Desk Accessories, Black Carbon>','Furnishings'),
(1448,'<Eldon 500 Class Desk Accessories>','Furnishings'),
(1449,'<Eldon Advantage Chair Mats for Low to Medium Pile Carpets>','Furnishings'),
(1450,'<Eldon Advantage Foldable Chair Mats for Low Pile Carpets>','Furnishings'),
(1451,'<Eldon Antistatic Chair Mats for Low to Medium Pile Carpets>','Furnishings'),
(1452,'<Eldon Base for stackable storage shelf, platinum>','Storage'),
(1453,'<Eldon Cleatmat Chair Mats for Medium Pile Carpets>','Furnishings'),
(1454,'<Eldon Cleatmat Plus Chair Mats for High Pile Carpets>','Furnishings'),
(1455,'<Eldon ClusterMat Chair Mat with Cordless Antistatic Protection>','Furnishings'),
(1456,'<Eldon Delta Triangular Chair Mat, 52" x 58", Clear>','Furnishings'),
(1457,'<Eldon Econocleat Chair Mats for Low Pile Carpets>','Furnishings'),
(1458,'<Eldon Executive Woodline II Desk Accessories, Mahogany>','Furnishings'),
(1459,'<Eldon Expressions Desk Accessory, Wood Pencil Holder, Oak>','Furnishings'),
(1460,'<Eldon Expressions Desk Accessory, Wood Photo Frame, Mahogany>','Furnishings'),
(1461,'<Eldon Expressions Punched Metal & Wood Desk Accessories, Black & Cherry>','Furnishings'),
(1462,'<Eldon Expressions Punched Metal & Wood Desk Accessories, Pewter & Cherry>','Furnishings'),
(1463,'<Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood>','Furnishings'),
(1464,'<Eldon Expressions Wood and Plastic Desk Accessories, Oak>','Furnishings'),
(1465,'<Eldon Expressions Wood Desk Accessories, Oak>','Furnishings'),
(1466,'<Eldon File Chest Portable File>','Storage'),
(1467,'<Eldon Fold ''N Roll Cart System>','Storage'),
(1468,'<Eldon Gobal File Keepers>','Storage'),
(1469,'<Eldon ImÃ ge Series Desk Accessories, Clear>','Furnishings'),
(1470,'<Eldon Image Series Black Desk Accessories>','Furnishings'),
(1471,'<Eldon Image Series Desk Accessories, Burgundy>','Furnishings'),
(1472,'<Eldon Image Series Desk Accessories, Ebony>','Furnishings'),
(1473,'<Eldon Mobile Mega Data Cart  Mega Stackable  Add-On Trays>','Storage'),
(1474,'<Eldon Portable Mobile Manager>','Storage'),
(1475,'<Eldon ProFile File ''N Store Portable File Tub Letter/Legal Size Black>','Storage'),
(1476,'<Eldon Radial Chair Mat for Low to Medium Pile Carpets>','Furnishings'),
(1477,'<Eldon Regeneration Recycled Desk Accessories, Black>','Furnishings'),
(1478,'<Eldon Regeneration Recycled Desk Accessories, Smoke>','Furnishings'),
(1479,'<Eldon Shelf Savers Cubes and Bins>','Storage'),
(1480,'<Eldon Simplefile Box Office>','Storage'),
(1481,'<Eldon Spacemaker Box, Quick-Snap Lid, Clear>','Art'),
(1482,'<Eldon Stackable Tray, Side-Load, Legal, Smoke>','Furnishings'),
(1483,'<Eldon Wave Desk Accessories>','Furnishings'),
(1484,'<Electrix 20W Halogen Replacement Bulb for Zoom-In Desk Lamp>','Furnishings'),
(1485,'<Electrix Fluorescent Magnifier Lamps & Weighted Base>','Furnishings'),
(1486,'<Electrix Halogen Magnifier Lamp>','Furnishings'),
(1487,'<Electrix Incandescent Magnifying Lamp, Black>','Furnishings'),
(1488,'<Elite 5" Scissors>','Supplies'),
(1489,'<Embossed Ink Jet Note Cards>','Paper'),
(1490,'<Enermax Acrylux Wireless Keyboard>','Accessories'),
(1491,'<Enermax Briskie RF Wireless Keyboard and Mouse Combo>','Accessories'),
(1492,'<Eureka Recycled Copy Paper 8 1/2" x 11", Ream>','Paper'),
(1493,'<Eureka Sanitaire  Multi-Pro Heavy-Duty Upright, Disposable Bags>','Appliances'),
(1494,'<Eureka The Boss Cordless Rechargeable Stick Vac>','Appliances'),
(1495,'<Eureka The Boss Lite 10-Amp Upright Vacuum, Blue>','Appliances'),
(1496,'<Euro-Pro Shark Turbo Vacuum>','Appliances'),
(1497,'<Executive Impressions 10" Spectator Wall Clock>','Furnishings'),
(1498,'<Executive Impressions 12" Wall Clock>','Furnishings'),
(1499,'<Executive Impressions 13" Chairman Wall Clock>','Furnishings'),
(1500,'<Executive Impressions 13-1/2" Indoor/Outdoor Wall Clock>','Furnishings'),
(1501,'<Executive Impressions 14" Contract Wall Clock>','Furnishings'),
(1502,'<Executive Impressions 14" Two-Color Numerals Wall Clock>','Furnishings'),
(1503,'<Executive Impressions 8-1/2" Career Panel/Partition Cubicle Clock>','Furnishings'),
(1504,'<Executive Impressions Supervisor Wall Clock>','Furnishings'),
(1505,'<Faber Castell Col-Erase Pencils>','Art'),
(1506,'<Fellowes 8 Outlet Superior Workstation Surge Protector>','Appliances'),
(1507,'<Fellowes 8 Outlet Superior Workstation Surge Protector w/o Phone/Fax/Modem Protection>','Appliances'),
(1508,'<Fellowes Advanced Computer Series Surge Protectors>','Appliances'),
(1509,'<Fellowes Bankers Box Recycled Super Stor/Drawer>','Storage'),
(1510,'<Fellowes Bankers Box Staxonsteel Drawer File/Stacking System>','Storage'),
(1511,'<Fellowes Bankers Box Stor/Drawer Steel Plus>','Storage'),
(1512,'<Fellowes Bases and Tops For Staxonsteel/High-Stak Systems>','Storage'),
(1513,'<Fellowes Basic Home/Office Series Surge Protectors>','Appliances'),
(1514,'<Fellowes Binding Cases>','Binders'),
(1515,'<Fellowes Black Plastic Comb Bindings>','Binders'),
(1516,'<Fellowes Command Center 5-outlet power strip>','Appliances'),
(1517,'<Fellowes High-Stak Drawer Files>','Storage'),
(1518,'<Fellowes Mighty 8 Compact Surge Protector>','Appliances'),
(1519,'<Fellowes Mobile File Cart, Black>','Storage'),
(1520,'<Fellowes Neat Ideas Storage Cubes>','Storage'),
(1521,'<Fellowes Officeware Wire Shelving>','Storage'),
(1522,'<Fellowes PB200 Plastic Comb Binding Machine>','Binders'),
(1523,'<Fellowes PB300 Plastic Comb Binding Machine>','Binders'),
(1524,'<Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind>','Binders'),
(1525,'<Fellowes Personal Hanging Folder Files, Navy>','Storage'),
(1526,'<Fellowes Powershred HS-440 4-Sheet High Security Shredder>','Machines'),
(1527,'<Fellowes Premier Superior Surge Suppressor, 10-Outlet, With Phone and Remote>','Appliances'),
(1528,'<Fellowes Recycled Storage Drawers>','Storage'),
(1529,'<Fellowes Staxonsteel Drawer Files>','Storage'),
(1530,'<Fellowes Stor/Drawer Steel Plus Storage Drawers>','Storage'),
(1531,'<Fellowes Strictly Business Drawer File, Letter/Legal Size>','Storage'),
(1532,'<Fellowes Super Stor/Drawer>','Storage'),
(1533,'<Fellowes Super Stor/Drawer Files>','Storage'),
(1534,'<Fellowes Superior 10 Outlet Split Surge Protector>','Appliances'),
(1535,'<Fellowes Twister Kit, Gray/Clear, 3/pkg>','Binders'),
(1536,'<File Shuttle I and Handi-File>','Storage'),
(1537,'<File Shuttle II and Handi-File, Black>','Storage'),
(1538,'<First Data FD10 PIN Pad>','Accessories'),
(1539,'<First Data TMFD35 PIN Pad>','Accessories'),
(1540,'<Fiskars 8" Scissors, 2/Pack>','Supplies'),
(1541,'<Fiskars Home & Office Scissors>','Supplies'),
(1542,'<Fiskars Softgrip Scissors>','Supplies'),
(1543,'<Fiskars Spring-Action Scissors>','Supplies'),
(1544,'<Flat Face Poster Frame>','Furnishings'),
(1545,'<Flexible Leather- Look Classic Collection Ring Binder>','Binders'),
(1546,'<Floodlight Indoor Halogen Bulbs, 1 Bulb per Pack, 60 Watts>','Furnishings'),
(1547,'<Fluorescent Highlighters by Dixon>','Art'),
(1548,'<G.E. Halogen Desk Lamp Bulbs>','Furnishings'),
(1549,'<G.E. Longer-Life Indoor Recessed Floodlight Bulbs>','Furnishings'),
(1550,'<GBC Binding covers>','Binders'),
(1551,'<GBC DocuBind 200 Manual Binding Machine>','Binders'),
(1552,'<GBC DocuBind 300 Electric Binding Machine>','Binders'),
(1553,'<GBC DocuBind P100 Manual Binding Machine>','Binders'),
(1554,'<GBC DocuBind P400 Electric Binding System>','Binders'),
(1555,'<GBC DocuBind P50 Personal Binding Machine>','Binders'),
(1556,'<GBC DocuBind TL200 Manual Binding Machine>','Binders'),
(1557,'<GBC Durable Plastic Covers>','Binders'),
(1558,'<GBC Imprintable Covers>','Binders'),
(1559,'<GBC Instant Index System for Binding Systems>','Binders'),
(1560,'<GBC Instant Report Kit>','Binders'),
(1561,'<GBC Laser Imprintable Binding System Covers, Desert Sand>','Binders'),
(1562,'<GBC Linen Binding Covers>','Binders'),
(1563,'<GBC Personal VeloBind Strips>','Binders'),
(1564,'<GBC Plastic Binding Combs>','Binders'),
(1565,'<GBC Poly Designer Binding Covers>','Binders'),
(1566,'<GBC Premium Transparent Covers with Diagonal Lined Pattern>','Binders'),
(1567,'<GBC Pre-Punched Binding Paper, Plastic, White, 8-1/2" x 11">','Binders'),
(1568,'<GBC Prepunched Paper, 19-Hole, for Binding Systems, 24-lb>','Binders'),
(1569,'<GBC Prestige Therm-A-Bind Covers>','Binders'),
(1570,'<GBC ProClick 150 Presentation Binding System>','Binders'),
(1571,'<GBC Recycled Grain Textured Covers>','Binders'),
(1572,'<GBC Recycled Regency Composition Covers>','Binders'),
(1573,'<GBC Recycled VeloBinder Covers>','Binders'),
(1574,'<GBC Standard Plastic Binding Systems'' Combs>','Binders'),
(1575,'<GBC Standard Recycled Report Covers, Clear Plastic Sheets>','Binders'),
(1576,'<GBC Standard Therm-A-Bind Covers>','Binders'),
(1577,'<GBC Therma-A-Bind 250T Electric Binding System>','Binders'),
(1578,'<GBC Twin Loop Wire Binding Elements>','Binders'),
(1579,'<GBC Twin Loop Wire Binding Elements, 9/16" Spine, Black>','Binders'),
(1580,'<GBC VeloBind Cover Sets>','Binders'),
(1581,'<GBC Velobind Prepunched Cover Sets, Regency Series>','Binders'),
(1582,'<GBC VeloBinder Electric Binding Machine>','Binders'),
(1583,'<GBC VeloBinder Manual Binding System>','Binders'),
(1584,'<GBC White Gloss Covers, Plain Front>','Binders'),
(1585,'<GBC Wire Binding Combs>','Binders'),
(1586,'<GBC Wire Binding Strips>','Binders'),
(1587,'<GE 30524EE4>','Phones'),
(1588,'<GE 4 Foot Flourescent Tube, 40 Watt>','Furnishings'),
(1589,'<GE 48" Fluorescent Tube, Cool White Energy Saver, 34 Watts, 30/Box>','Furnishings'),
(1590,'<GE DSL Phone Line Filter>','Phones'),
(1591,'<GE General Purpose, Extra Long Life, Showcase & Floodlight Incandescent Bulbs>','Furnishings'),
(1592,'<Gear Head AU3700S Headset>','Phones'),
(1593,'<Geemarc AmpliPOWER60>','Phones'),
(1594,'<Geographics Note Cards, Blank, White, 8 1/2" x 11">','Paper'),
(1595,'<Global Adaptabilites Bookcase, Cherry/Storm Gray Finish>','Bookcases'),
(1596,'<Global Adaptabilities Conference Tables>','Tables'),
(1597,'<Global Airflow Leather Mesh Back Chair, Black>','Chairs'),
(1598,'<Global Armless Task Chair, Royal Blue>','Chairs'),
(1599,'<Global Chrome Stack Chair>','Chairs'),
(1600,'<Global Comet Stacking Arm Chair>','Chairs'),
(1601,'<Global Comet Stacking Armless Chair>','Chairs'),
(1602,'<Global Deluxe High-Back Manager''s Chair>','Chairs'),
(1603,'<Global Deluxe High-Back Office Chair in Storm>','Chairs'),
(1604,'<Global Deluxe Office Fabric Chairs>','Chairs'),
(1605,'<Global Deluxe Stacking Chair, Gray>','Chairs'),
(1606,'<Global Deluxe Steno Chair>','Chairs'),
(1607,'<Global Enterprise Series Seating High-Back Swivel/Tilt Chairs>','Chairs'),
(1608,'<Global Enterprise Series Seating Low-Back Swivel/Tilt Chairs>','Chairs'),
(1609,'<Global Ergonomic Managers Chair>','Chairs'),
(1610,'<Global Executive Mid-Back Manager''s Chair>','Chairs'),
(1611,'<Global Fabric Manager''s Chair, Dark Gray>','Chairs'),
(1612,'<Global Geo Office Task Chair, Gray>','Chairs'),
(1613,'<Global Highback Leather Tilter in Burgundy>','Chairs'),
(1614,'<Global High-Back Leather Tilter, Burgundy>','Chairs'),
(1615,'<Global Leather & Oak Executive Chair, Burgundy>','Chairs'),
(1616,'<Global Leather and Oak Executive Chair, Black>','Chairs'),
(1617,'<Global Leather Executive Chair>','Chairs'),
(1618,'<Global Leather Highback Executive Chair with Pneumatic Height Adjustment, Black>','Chairs'),
(1619,'<Global Leather Task Chair, Black>','Chairs'),
(1620,'<Global Low Back Tilter Chair>','Chairs'),
(1621,'<Global Manager''s Adjustable Task Chair, Storm>','Chairs'),
(1622,'<Global Push Button Manager''s Chair, Indigo>','Chairs'),
(1623,'<Global Stack Chair with Arms, Black>','Chairs'),
(1624,'<Global Stack Chair without Arms, Black>','Chairs'),
(1625,'<Global Super Steno Chair>','Chairs'),
(1626,'<Global Task Chair, Black>','Chairs'),
(1627,'<Global Troy Executive Leather Low-Back Tilter>','Chairs'),
(1628,'<Global Value Mid-Back Manager''s Chair, Gray>','Chairs'),
(1629,'<Global Value Steno Chair, Gray>','Chairs'),
(1630,'<Global Wood Trimmed Manager''s Task Chair, Khaki>','Chairs'),
(1631,'<Globe Weis Peel & Seel First Class Envelopes>','Envelopes'),
(1632,'<Google Nexus 5>','Phones'),
(1633,'<Gould Plastics 18-Pocket Panel Bin, 34w x 5-1/4d x 20-1/2h>','Storage'),
(1634,'<Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5-1/4d x 20-1/2h, Black>','Storage'),
(1635,'<Grandstream GXP1160 VoIP phone>','Phones'),
(1636,'<Grandstream GXP2100 Mainstream Business Phone>','Phones'),
(1637,'<Great White Multi-Use Recycled Paper (20Lb. and 84 Bright)>','Paper'),
(1638,'<Green Bar Computer Printout Paper>','Paper'),
(1639,'<Green Canvas Binder for 8-1/2" x 14" Sheets>','Binders'),
(1640,'<Griffin GC17055 Auxiliary Audio Cable>','Phones'),
(1641,'<Griffin GC36547 PowerJolt SE Lightning Charger>','Phones'),
(1642,'<GuestStacker Chair with Chrome Finish Legs>','Chairs'),
(1643,'<Hammermill Color Copier Paper (28Lb. and 96 Bright)>','Paper'),
(1644,'<Hammermill CopyPlus Copy Paper (20Lb. and 84 Bright)>','Paper'),
(1645,'<Hand-Finished Solid Wood Document Frame>','Furnishings'),
(1646,'<Hanging Personal Folder File>','Storage'),
(1647,'<Harbour Creations 67200 Series Stacking Chairs>','Chairs'),
(1648,'<Harmony Air Purifier>','Appliances'),
(1649,'<Harmony HEPA Quiet Air Purifiers>','Appliances'),
(1650,'<Heavy-Duty E-Z-D Binders>','Binders'),
(1651,'<Hewlett Packard 310 Color Digital Copier>','Copiers'),
(1652,'<Hewlett Packard 610 Color Digital Copier / Printer>','Copiers'),
(1653,'<Hewlett Packard LaserJet 3310 Copier>','Copiers'),
(1654,'<Hewlett-Packard Deskjet D4360 Printer>','Machines'),
(1655,'<High Speed Automatic Electric Letter Opener>','Supplies'),
(1656,'<High-Back Leather Manager''s Chair>','Chairs'),
(1657,'<Holmes 99% HEPA Air Purifier>','Appliances'),
(1658,'<Holmes Cool Mist Humidifier for the Whole House with 8-Gallon Output per Day, Extended Life Filter>','Appliances'),
(1659,'<Holmes HEPA Air Purifier>','Appliances'),
(1660,'<Holmes Odor Grabber>','Appliances'),
(1661,'<Holmes Replacement Filter for HEPA Air Cleaner, Medium Room>','Appliances'),
(1662,'<Holmes Visible Mist Ultrasonic Humidifier with 2.3-Gallon Output per Day, Replacement Filter>','Appliances'),
(1663,'<Home/Office Personal File Carts>','Storage'),
(1664,'<Hon 2090 “Pillow Soft” Series Mid Back Swivel/Tilt Chairs>','Chairs'),
(1665,'<Hon 2111 Invitation Series Corner Table>','Tables'),
(1666,'<Hon 2111 Invitation Series Straight Table>','Tables'),
(1667,'<Hon 30" x 60" Table with Locking Drawer>','Tables'),
(1668,'<Hon 4060 Series Tables>','Tables'),
(1669,'<Hon 4070 Series Pagoda Armless Upholstered Stacking Chairs>','Chairs'),
(1670,'<Hon 4070 Series Pagoda Round Back Stacking Chairs>','Chairs'),
(1671,'<Hon 4700 Series Mobuis Mid-Back Task Chairs with Adjustable Arms>','Chairs'),
(1672,'<Hon 4-Shelf Metal Bookcases>','Bookcases'),
(1673,'<Hon 5100 Series Wood Tables>','Tables'),
(1674,'<HON 5400 Series Task Chairs for Big and Tall>','Chairs'),
(1675,'<Hon 61000 Series Interactive Training Tables>','Tables'),
(1676,'<Hon 94000 Series Round Tables>','Tables'),
(1677,'<Hon Comfortask Task/Swivel Chairs>','Chairs'),
(1678,'<Hon Deluxe Fabric Upholstered Stacking Chairs>','Chairs'),
(1679,'<Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back>','Chairs'),
(1680,'<Hon Deluxe Fabric Upholstered Stacking Chairs, Squared Back>','Chairs'),
(1681,'<Hon Every-Day Chair Series Swivel Task Chairs>','Chairs'),
(1682,'<Hon Every-Day Series Multi-Task Chairs>','Chairs'),
(1683,'<Hon GuestStacker Chair>','Chairs'),
(1684,'<Hon Metal Bookcases, Black>','Bookcases'),
(1685,'<Hon Metal Bookcases, Putty>','Bookcases'),
(1686,'<Hon Multipurpose Stacking Arm Chairs>','Chairs'),
(1687,'<Hon Non-Folding Utility Tables>','Tables'),
(1688,'<Hon Olson Stacker Stools>','Chairs'),
(1689,'<Hon Pagoda Stacking Chairs>','Chairs'),
(1690,'<Hon Practical Foundations 30 x 60 Training Table, Light Gray/Charcoal>','Tables'),
(1691,'<Hon Racetrack Conference Tables>','Tables'),
(1692,'<Hon Valutask Swivel Chairs>','Chairs'),
(1693,'<Honeywell Enviracaire Portable HEPA Air Cleaner for 16'' x 20'' Room>','Appliances'),
(1694,'<Honeywell Quietcare HEPA Air Cleaner>','Appliances'),
(1695,'<Hoover Commercial Soft Guard Upright Vacuum And Disposable Filtration Bags>','Appliances'),
(1696,'<Hoover Commercial SteamVac>','Appliances'),
(1697,'<Hoover Replacement Belts For Soft Guard & Commercial Ltweight Upright Vacs, 2/Pk>','Appliances'),
(1698,'<Hoover Shoulder Vac Commercial Portable Vacuum>','Appliances'),
(1699,'<Hoover Upright Vacuum With Dirt Cup>','Appliances'),
(1700,'<Hoover WindTunnel Plus Canister Vacuum>','Appliances'),
(1701,'<Hot File 7-Pocket, Floor Stand>','Storage'),
(1702,'<Howard Miller 11-1/2" Diameter Brentwood Wall Clock>','Furnishings'),
(1703,'<Howard Miller 11-1/2" Diameter Grantwood Wall Clock>','Furnishings'),
(1704,'<Howard Miller 11-1/2" Diameter Ridgewood Wall Clock>','Furnishings'),
(1705,'<Howard Miller 12" Round Wall Clock>','Furnishings'),
(1706,'<Howard Miller 13" Diameter Goldtone Round Wall Clock>','Furnishings'),
(1707,'<Howard Miller 13" Diameter Pewter Finish Round Wall Clock>','Furnishings'),
(1708,'<Howard Miller 13-1/2" Diameter Rosebrook Wall Clock>','Furnishings'),
(1709,'<Howard Miller 13-3/4" Diameter Brushed Chrome Round Wall Clock>','Furnishings'),
(1710,'<Howard Miller 14-1/2" Diameter Chrome Round Wall Clock>','Furnishings'),
(1711,'<Howard Miller 16" Diameter Gallery Wall Clock>','Furnishings'),
(1712,'<Howard Miller Distant Time Traveler Alarm Clock>','Furnishings'),
(1713,'<HP Office Recycled Paper (20Lb. and 87 Bright)>','Paper'),
(1714,'<HP Officejet Pro 8600 e-All-In-One Printer, Copier, Scanner, Fax>','Machines'),
(1715,'<HP Standard 104 key PS/2 Keyboard>','Accessories'),
(1716,'<HTC One>','Phones'),
(1717,'<HTC One Mini>','Phones'),
(1718,'<Hunt BOSTON Model 1606 High-Volume Electric Pencil Sharpener, Beige>','Art'),
(1719,'<Hunt BOSTON Vista Battery-Operated Pencil Sharpener, Black>','Art'),
(1720,'<Hunt PowerHouse Electric Pencil Sharpener, Blue>','Art'),
(1721,'<Hypercom P1300 Pinpad>','Accessories'),
(1722,'<I Need''s 3d Hello Kitty Hybrid Silicone Case Cover for HTC One X 4g with 3d Hello Kitty Stylus Pen Green/pink>','Phones'),
(1723,'<i.Sound Portable Power - 8000 mAh>','Phones'),
(1724,'<Ibico EB-19 Dual Function Manual Binding System>','Binders'),
(1725,'<Ibico EPK-21 Electric Binding System>','Binders'),
(1726,'<Ibico Hi-Tech Manual Binding System>','Binders'),
(1727,'<Ibico Ibimaster 300 Manual Binding System>','Binders'),
(1728,'<Ibico Laser Imprintable Binding System Covers>','Binders'),
(1729,'<Ibico Plastic and Wire Spiral Binding Combs>','Binders'),
(1730,'<Ibico Plastic Spiral Binding Combs>','Binders'),
(1731,'<Ibico Presentation Index for Binding Systems>','Binders'),
(1732,'<Ibico Recycled Grain-Textured Covers>','Binders'),
(1733,'<Ibico Recycled Linen-Style Covers>','Binders'),
(1734,'<Ibico Standard Transparent Covers>','Binders'),
(1735,'<IBM Multi-Purpose Copy Paper, 8 1/2 x 11", Case>','Paper'),
(1736,'<Iceberg Mobile Mega Data/Printer Cart >','Storage'),
(1737,'<Iceberg Nesting Folding Chair, 19w x 6d x 43h>','Chairs'),
(1738,'<Iceberg OfficeWorks 42" Round Tables>','Tables'),
(1739,'<Ideal Clamps>','Fasteners'),
(1740,'<iHome FM Clock Radio with Lightning Dock>','Phones'),
(1741,'<iKross Bluetooth Portable Keyboard + Cell Phone Stand Holder + Brush for Apple iPhone 5S 5C 5, 4S 4>','Phones'),
(1742,'<Imation Bio 2GB USB Flash Drive Imation Corp>','Accessories'),
(1743,'<Imation Bio 8GB USB Flash Drive Imation Corp>','Accessories'),
(1744,'<Imation 16GB Mini TravelDrive USB 2.0 Flash Drive>','Accessories'),
(1745,'<Imation 30456 USB Flash Drive 8GB>','Accessories'),
(1746,'<Imation 32GB Pocket Pro USB 3.0 Flash Drive - 32 GB - Black - 1 P ...>','Accessories'),
(1747,'<Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive>','Accessories'),
(1748,'<Imation 8GB Mini TravelDrive USB 2.0 Flash Drive>','Accessories'),
(1749,'<Imation Clip USB flash drive - 8 GB>','Accessories'),
(1750,'<Imation Secure Drive + Hardware Encrypted USB flash drive - 16 GB>','Accessories'),
(1751,'<Imation Swivel Flash Drive USB flash drive - 8 GB>','Accessories'),
(1752,'<Imation USB 2.0 Swivel Flash Drive USB flash drive - 4 GB - Pink>','Accessories'),
(1753,'<Important Message Pads, 50 4-1/4 x 5-1/2 Forms per Pad>','Paper'),
(1754,'<Insertable Tab Post Binder Dividers>','Binders'),
(1755,'<Inter-Office Recycled Envelopes, Brown Kraft, Button-String,10" x 13" , 100/Box>','Envelopes'),
(1756,'<invisibleSHIELD by ZAGG Smudge-Free Screen Protector>','Phones'),
(1757,'<iOttie HLCRIO102 Car Mount>','Phones'),
(1758,'<iOttie XL Car Mount>','Phones'),
(1759,'<Iris Project Case>','Storage'),
(1760,'<It''s Hot Message Books with Stickers, 2 3/4" x 5">','Paper'),
(1761,'<Jabra BIZ 2300 Duo QD Duo Corded Headset>','Phones'),
(1762,'<Jabra SPEAK 410>','Phones'),
(1763,'<Jackery Bar Premium Fast-charging Portable Charger>','Phones'),
(1764,'<Jawbone MINI JAMBOX Wireless Bluetooth Speaker>','Phones'),
(1765,'<JBL Micro Wireless Portable Bluetooth Speaker>','Phones'),
(1766,'<Jensen SMPS-640 - speaker phone>','Phones'),
(1767,'<Jet-Pak Recycled Peel ''N'' Seal Padded Mailers>','Envelopes'),
(1768,'<JM Magazine Binder>','Binders'),
(1769,'<Kensington 4 Outlet MasterPiece Compact Power Control Center>','Appliances'),
(1770,'<Kensington 6 Outlet Guardian Standard Surge Protector>','Appliances'),
(1771,'<Kensington 6 Outlet MasterPiece HOMEOFFICE Power Control Center>','Appliances'),
(1772,'<Kensington 7 Outlet MasterPiece HOMEOFFICE Power Control Center>','Appliances'),
(1773,'<Kensington Expert Mouse Optical USB Trackball for PC or Mac>','Accessories'),
(1774,'<Kensington K72356US Mouse-in-a-Box USB Desktop Mouse>','Accessories'),
(1775,'<Kensington Orbit Wireless Mobile Trackball for PC and Mac>','Accessories'),
(1776,'<KeyTronic 6101 Series - Keyboard - Black>','Accessories'),
(1777,'<KeyTronic E03601U1 - Keyboard - Beige>','Accessories'),
(1778,'<KeyTronic KT400U2 - Keyboard - Black>','Accessories'),
(1779,'<KI Adjustable-Height Table>','Tables'),
(1780,'<KI Conference Tables>','Tables'),
(1781,'<Kingston Digital DataTraveler 16GB USB 2.0>','Accessories'),
(1782,'<Kingston Digital DataTraveler 32GB USB 2.0>','Accessories'),
(1783,'<Kingston Digital DataTraveler 64GB USB 2.0>','Accessories'),
(1784,'<Kleencut Forged Office Shears by Acme United Corporation>','Supplies'),
(1785,'<Konftel 250 Conference phone - Charcoal black>','Phones'),
(1786,'<Laminate Occasional Tables>','Tables'),
(1787,'<Large Capacity Hanging Post Binders>','Binders'),
(1788,'<Laser & Ink Jet Business Envelopes>','Envelopes'),
(1789,'<Leather Task Chair, Black>','Chairs'),
(1790,'<Lenovo 17-Key USB Numeric Keypad>','Accessories'),
(1791,'<Lesro Round Back Collection Coffee Table, End Table>','Tables'),
(1792,'<Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table>','Tables'),
(1793,'<Letter or Legal Size Expandable Poly String Tie Envelopes>','Envelopes'),
(1794,'<Letter Size Cart>','Storage'),
(1795,'<Letter/Legal File Tote with Clear Snap-On Lid, Black Granite>','Storage'),
(1796,'<Lexmark MX611dhe Monochrome Laser Printer>','Machines'),
(1797,'<Lexmark S315 Color Inkjet Printer>','Machines'),
(1798,'<LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite>','Phones'),
(1799,'<LG Electronics Tone+ HBS-730 Bluetooth Headset>','Phones'),
(1800,'<LG G3>','Phones'),
(1801,'<Lifetime Advantage Folding Chairs, 4/Carton>','Chairs'),
(1802,'<Linden 10" Round Wall Clock, Black>','Furnishings'),
(1803,'<Linden 12" Wall Clock With Oak Frame>','Furnishings'),
(1804,'<Lock-Up Easel ''Spel-Binder''>','Binders'),
(1805,'<Logitech 910-002974 M325 Wireless Mouse for Web Scrolling>','Accessories'),
(1806,'<Logitech B530 USB Headset - headset - Full size, Binaural>','Phones'),
(1807,'<Logitech ClearChat Comfort/USB Headset H390>','Accessories'),
(1808,'<Logitech Desktop MK120 Mouse and keyboard Combo>','Accessories'),
(1809,'<Logitech G13 Programmable Gameboard with LCD Display>','Accessories'),
(1810,'<Logitech G19 Programmable Gaming Keyboard>','Accessories'),
(1811,'<Logitech G35 7.1-Channel Surround Sound Headset>','Accessories'),
(1812,'<Logitech G430 Surround Sound Gaming Headset with Dolby 7.1 Technology>','Accessories'),
(1813,'<Logitech G500s Laser Gaming Mouse with Adjustable Weight Tuning>','Accessories'),
(1814,'<Logitech G600 MMO Gaming Mouse>','Accessories'),
(1815,'<Logitech G602 Wireless Gaming Mouse>','Accessories'),
(1816,'<Logitech G700s Rechargeable Gaming Mouse>','Accessories'),
(1817,'<Logitech Illuminated Ultrathin Keyboard with Backlighting>','Accessories'),
(1818,'<Logitech K350 2.4Ghz Wireless Keyboard>','Accessories'),
(1819,'<Logitech Keyboard K120>','Accessories'),
(1820,'<Logitech M510 Wireless Mouse>','Accessories'),
(1821,'<Logitech Media Keyboard K200>','Accessories'),
(1822,'<Logitech Mobile Speakerphone P710e - speaker phone>','Phones'),
(1823,'<Logitech Trackman Marble Mouse>','Accessories'),
(1824,'<Logitech Wireless Anywhere Mouse MX for PC and Mac>','Accessories'),
(1825,'<Logitech Wireless Gaming Headset G930>','Accessories'),
(1826,'<Logitech Wireless Headset H600 Over-The-Head Design>','Accessories'),
(1827,'<Logitech Wireless Headset h800>','Accessories'),
(1828,'<Logitech Wireless Marathon Mouse M705>','Accessories'),
(1829,'<Logitech Wireless Performance Mouse MX for PC and Mac>','Accessories'),
(1830,'<Logitech Wireless Touch Keyboard K400>','Accessories'),
(1831,'<Logitech Gaming G510s - Keyboard>','Accessories'),
(1832,'<Logitech Illuminated - Keyboard>','Accessories'),
(1833,'<Logitech LS21 Speaker System - PC Multimedia - 2.1-CH - Wired>','Accessories'),
(1834,'<Logitech MX Performance Wireless Mouse>','Accessories'),
(1835,'<Logitech P710e Mobile Speakerphone>','Accessories'),
(1836,'<Logitech VX Revolution Cordless Laser Mouse for Notebooks (Black)>','Accessories'),
(1837,'<Logitech Z-906 Speaker sys - home theater - 5.1-CH>','Accessories'),
(1838,'<Longer-Life Soft White Bulbs>','Furnishings'),
(1839,'<Lumber Crayons>','Art'),
(1840,'<Lunatik TT5L-002 Taktik Strike Impact Protection System for iPhone 5>','Phones'),
(1841,'<Luxo Adjustable Task Clamp Lamp>','Furnishings'),
(1842,'<Luxo Economy Swing Arm Lamp>','Furnishings'),
(1843,'<Luxo Professional Combination Clamp-On Lamps>','Furnishings'),
(1844,'<Luxo Professional Fluorescent Magnifier Lamp with Clamp-Mount Base>','Furnishings'),
(1845,'<Luxo Professional Magnifying Clamp-On Fluorescent Lamps>','Furnishings'),
(1846,'<Macally Suction Cup Mount>','Phones'),
(1847,'<Magna Visual Magnetic Picture Hangers>','Furnishings'),
(1848,'<Magnifier Swing Arm Lamp>','Furnishings'),
(1849,'<Manco Dry-Lighter Erasable Highlighter>','Art'),
(1850,'<Manila Recycled Extra-Heavyweight Clasp Envelopes, 6" x 9">','Envelopes'),
(1851,'<Martin Yale Chadless Opener Electric Letter Opener>','Supplies'),
(1852,'<Martin-Yale Premier Letter Opener>','Supplies'),
(1853,'<Master Big Foot Doorstop, Beige>','Furnishings'),
(1854,'<Master Caster Door Stop, Brown>','Furnishings'),
(1855,'<Master Caster Door Stop, Gray>','Furnishings'),
(1856,'<Master Caster Door Stop, Large Brown>','Furnishings'),
(1857,'<Master Caster Door Stop, Large Neon Orange>','Furnishings'),
(1858,'<Master Giant Foot Doorstop, Safety Yellow>','Furnishings'),
(1859,'<Maxell 4.7GB DVD+RW 3/Pack>','Accessories'),
(1860,'<Maxell 4.7GB DVD-R 5/Pack>','Accessories'),
(1861,'<Maxell 74 Minute CD-R Spindle, 50/Pack>','Accessories'),
(1862,'<Maxell 74 Minute CDR, 10/Pack>','Accessories'),
(1863,'<Maxell DVD-RAM Discs>','Accessories'),
(1864,'<Maxell LTO Ultrium - 800 GB>','Accessories'),
(1865,'<Mead 1st Gear 2" Zipper Binder, Asst. Colors>','Binders'),
(1866,'<Mediabridge Sport Armband iPhone 5s>','Phones'),
(1867,'<Memorex 25GB 6X Branded Blu-Ray Recordable Disc, 15/Pack>','Accessories'),
(1868,'<Memorex 25GB 6X Branded Blu-Ray Recordable Disc, 30/Pack>','Accessories'),
(1869,'<Memorex Froggy Flash Drive 4 GB>','Accessories'),
(1870,'<Memorex Froggy Flash Drive 8 GB>','Accessories'),
(1871,'<Memorex Micro Travel Drive 16 GB>','Accessories'),
(1872,'<Memorex Micro Travel Drive 32 GB>','Accessories'),
(1873,'<Memorex Micro Travel Drive 8 GB>','Accessories'),
(1874,'<Memorex Mini Travel Drive 16 GB USB 2.0 Flash Drive>','Accessories'),
(1875,'<Memorex Mini Travel Drive 32 GB USB 2.0 Flash Drive>','Accessories'),
(1876,'<Memorex Mini Travel Drive 64 GB USB 2.0 Flash Drive>','Accessories'),
(1877,'<Memorex Mini Travel Drive 8 GB USB 2.0 Flash Drive>','Accessories'),
(1878,'<Message Book, Phone, Wirebound Standard Line Memo, 2 3/4" X 5">','Paper'),
(1879,'<Message Book, Standard Line "While You Were Out", 5 1/2" X 4", 200 Sets/Book>','Paper'),
(1880,'<Message Book, Wirebound, Four 5 1/2" X 4" Forms/Pg., 200 Dupl. Sets/Book>','Paper'),
(1881,'<Metal Folding Chairs, Beige, 4/Carton>','Chairs'),
(1882,'<Micro Innovations USB RF Wireless Keyboard with Mouse>','Accessories'),
(1883,'<Micropad Numeric Keypads>','Accessories'),
(1884,'<Microsoft Arc Touch Mouse>','Accessories'),
(1885,'<Microsoft Natural Ergonomic Keyboard 4000>','Accessories'),
(1886,'<Microsoft Natural Keyboard Elite>','Accessories'),
(1887,'<Microsoft Sculpt Comfort Mouse>','Accessories'),
(1888,'<Microsoft Wireless Mobile Mouse 4000>','Accessories'),
(1889,'<Mini 13-1/2 Capacity Data Binder Rack, Pearl>','Storage'),
(1890,'<Mitel 5320 IP Phone VoIP phone>','Phones'),
(1891,'<Mitel MiVoice 5330e IP Phone>','Phones'),
(1892,'<Mobile Personal File Cube>','Storage'),
(1893,'<Model L Table or Wall-Mount Pencil Sharpener>','Art'),
(1894,'<Mophie Juice Pack Helium for iPhone>','Phones'),
(1895,'<Motorla HX550 Universal Bluetooth Headset>','Phones'),
(1896,'<Motorola HK250 Universal Bluetooth Headset>','Phones'),
(1897,'<Motorola L703CM>','Phones'),
(1898,'<Motorola L804>','Phones'),
(1899,'<Motorola Moto X>','Phones'),
(1900,'<Multicolor Computer Printout Paper>','Paper'),
(1901,'<Multi-Use Personal File Cart and Caster Set, Three Stacking Bins>','Storage'),
(1902,'<Neat Ideas Personal Hanging Folder Files, Black>','Storage'),
(1903,'<NETGEAR AC1750 Dual Band Gigabit Smart WiFi Router>','Accessories'),
(1904,'<NETGEAR N750 Dual Band Wi-Fi Gigabit Router>','Accessories'),
(1905,'<netTALK DUO VoIP Telephone Service>','Phones'),
(1906,'<Newell 307>','Art'),
(1907,'<Newell 308>','Art'),
(1908,'<Newell 309>','Art'),
(1909,'<Newell 31>','Art'),
(1910,'<Newell 310>','Art'),
(1911,'<Newell 311>','Art'),
(1912,'<Newell 312>','Art'),
(1913,'<Newell 313>','Art'),
(1914,'<Newell 314>','Art'),
(1915,'<Newell 317>','Art'),
(1916,'<Newell 318>','Art'),
(1917,'<Newell 319>','Art'),
(1918,'<Newell 32>','Art'),
(1919,'<Newell 320>','Art'),
(1920,'<Newell 321>','Art'),
(1921,'<Newell 322>','Art'),
(1922,'<Newell 323>','Art'),
(1923,'<Newell 324>','Art'),
(1924,'<Newell 325>','Art'),
(1925,'<Newell 326>','Art'),
(1926,'<Newell 327>','Art'),
(1927,'<Newell 328>','Art'),
(1928,'<Newell 329>','Art'),
(1929,'<Newell 33>','Art'),
(1930,'<Newell 330>','Art'),
(1931,'<Newell 332>','Art'),
(1932,'<Newell 333>','Art'),
(1933,'<Newell 334>','Art'),
(1934,'<Newell 335>','Art'),
(1935,'<Newell 336>','Art'),
(1936,'<Newell 338>','Art'),
(1937,'<Newell 339>','Art'),
(1938,'<Newell 34>','Art'),
(1939,'<Newell 341>','Art'),
(1940,'<Newell 343>','Art'),
(1941,'<Newell 344>','Art'),
(1942,'<Newell 345>','Art'),
(1943,'<Newell 346>','Art'),
(1944,'<Newell 347>','Art'),
(1945,'<Newell 348>','Art'),
(1946,'<Newell 35>','Art'),
(1947,'<Newell 350>','Art'),
(1948,'<Newell 351>','Art'),
(1949,'<Newell 3-Hole Punched Plastic Slotted Magazine Holders for Binders>','Binders'),
(1950,'<Newell Chalk Holder>','Art'),
(1951,'<Nokia Lumia 521 (T-Mobile)>','Phones'),
(1952,'<Nokia Lumia 925>','Phones'),
(1953,'<Nontoxic Chalk>','Art'),
(1954,'<Nortel Business Series Terminal T7208 Digital phone>','Phones'),
(1955,'<Nortel Meridian M3904 Professional Digital phone>','Phones'),
(1956,'<Novimex Fabric Task Chair>','Chairs'),
(1957,'<Novimex High-Tech Fabric Mesh Task Chair>','Chairs'),
(1958,'<Novimex Swivel Fabric Task Chair>','Chairs'),
(1959,'<Novimex Turbo Task Chair>','Chairs'),
(1960,'<Nu-Dell Executive Frame>','Furnishings'),
(1961,'<Nu-Dell Float Frame 11 x 14 1/2>','Furnishings'),
(1962,'<Nu-Dell Leatherette Frames>','Furnishings'),
(1963,'<Nu-Dell Oak Frame>','Furnishings'),
(1964,'<Office Impressions Heavy Duty Welded Shelving & Multimedia Storage Drawers>','Storage'),
(1965,'<Office Star - Contemporary Swivel Chair with Padded Adjustable Arms and Flex Back>','Chairs'),
(1966,'<Office Star - Contemporary Task Swivel Chair>','Chairs'),
(1967,'<Office Star - Contemporary Task Swivel chair with Loop Arms, Charcoal>','Chairs'),
(1968,'<Office Star - Ergonomic Mid Back Chair with 2-Way Adjustable Arms>','Chairs'),
(1969,'<Office Star - Ergonomically Designed Knee Chair>','Chairs'),
(1970,'<Office Star - Mesh Screen back chair with Vinyl seat>','Chairs'),
(1971,'<Office Star - Mid Back Dual function Ergonomic High Back Chair with 2-Way Adjustable Arms>','Chairs'),
(1972,'<Office Star - Professional Matrix Back Chair with 2-to-1 Synchro Tilt and Mesh Fabric Seat>','Chairs'),
(1973,'<Office Star - Task Chair with Contemporary Loop Arms>','Chairs'),
(1974,'<Office Star Flex Back Scooter Chair with Aluminum Finish Frame>','Chairs'),
(1975,'<Office Star Flex Back Scooter Chair with White Frame>','Chairs'),
(1976,'<OIC #2 Pencils, Medium Soft>','Art'),
(1977,'<OIC Binder Clips>','Fasteners'),
(1978,'<OIC Binder Clips, Mini, 1/4" Capacity, Black>','Fasteners'),
(1979,'<OIC Bulk Pack Metal Binder Clips>','Fasteners'),
(1980,'<OIC Colored Binder Clips, Assorted Sizes>','Fasteners'),
(1981,'<OIC Stacking Trays>','Furnishings'),
(1982,'<OIC Thumb-Tacks>','Fasteners'),
(1983,'<Okidata B400 Printer>','Machines'),
(1984,'<Okidata B401 Printer>','Machines'),
(1985,'<Okidata C331dn Printer>','Machines'),
(1986,'<Okidata MB491 Multifunction Printer>','Machines'),
(1987,'<Okidata MB760 Printer>','Machines'),
(1988,'<Ooma Telo VoIP Home Phone System>','Phones'),
(1989,'<O''Sullivan 2-Door Barrister Bookcase in Odessa Pine>','Bookcases'),
(1990,'<O''Sullivan 2-Shelf Heavy-Duty Bookcases>','Bookcases'),
(1991,'<O''Sullivan 3-Shelf Heavy-Duty Bookcases>','Bookcases'),
(1992,'<O''Sullivan 4-Shelf Bookcase in Odessa Pine>','Bookcases'),
(1993,'<O''Sullivan 5-Shelf Heavy-Duty Bookcases>','Bookcases'),
(1994,'<O''Sullivan Cherrywood Estates Traditional Bookcase>','Bookcases'),
(1995,'<O''Sullivan Elevations Bookcase, Cherry Finish>','Bookcases')


----------------------------------------------------------------------------------------------------------------------------------First batch
INSERT INTO dbo.DimProduct(ProductKey,ProductName,ProductCategory)
VALUES (1996,'<O''Sullivan Living Dimensions 2-Shelf Bookcases>','Bookcases'),
(1997,'<O''Sullivan Living Dimensions 3-Shelf Bookcases>','Bookcases'),
(1998,'<O''Sullivan Manor Hill 2-Door Library in Brianna Oak>','Bookcases'),
(1999,'<OtterBox Commuter Series Case - iPhone 5 & 5s>','Phones'),
(2000,'<OtterBox Commuter Series Case - Samsung Galaxy S4>','Phones'),
(2001,'<OtterBox Defender Series Case - iPhone 5c>','Phones'),
(2002,'<OtterBox Defender Series Case - Samsung Galaxy S4>','Phones'),
(2003,'<Padded Folding Chairs, Black, 4/Carton>','Chairs'),
(2004,'<Panasonic KP-150 Electric Pencil Sharpener>','Art'),
(2005,'<Panasonic KP-310 Heavy-Duty Electric Pencil Sharpener>','Art'),
(2006,'<Panasonic KP-350BK Electric Pencil Sharpener with Auto Stop>','Art'),
(2007,'<Panasonic KP-380BK Classic Electric Pencil Sharpener>','Art'),
(2008,'<Panasonic KP-4ABK Battery-Operated Pencil Sharpener>','Art'),
(2009,'<Panasonic KX MB2061 Multifunction Printer>','Machines'),
(2010,'<Panasonic KX MC6040 Color Laser Multifunction Printer>','Machines'),
(2011,'<Panasonic KX T7731-B Digital phone>','Phones'),
(2012,'<Panasonic KX T7736-B Digital phone>','Phones'),
(2013,'<Panasonic KX TS208W Corded phone>','Phones'),
(2014,'<Panasonic KX TS3282B Corded phone>','Phones'),
(2015,'<Panasonic KX TS3282W Corded phone>','Phones'),
(2016,'<Panasonic KX-TG6844B Expandable Digital Cordless Telephone>','Phones'),
(2017,'<Panasonic KX-TG9541B DECT 6.0 Digital 2-Line Expandable Cordless Phone With Digital Answering System>','Phones'),
(2018,'<Panasonic Kx-TS550>','Phones'),
(2019,'<Pastel Pink Envelopes>','Envelopes'),
(2020,'<PayAnywhere Card Reader>','Phones'),
(2021,'<Peel & Seel Envelopes>','Envelopes'),
(2022,'<Peel & Seel Recycled Catalog Envelopes, Brown>','Envelopes'),
(2023,'<Peel & Stick Add-On Corner Pockets>','Binders'),
(2024,'<Peel-Off China Markers>','Art'),
(2025,'<Pencil and Crayon Sharpener>','Art'),
(2026,'<Performers Binder/Pad Holder, Black>','Binders'),
(2027,'<Perixx PERIBOARD-512B, Ergonomic Split Keyboard>','Accessories'),
(2028,'<Perma STOR-ALL Hanging File Box, 13 1/8"W x 12 1/4"D x 10 1/2"H>','Storage'),
(2029,'<Permanent Self-Adhesive File Folder Labels for Typewriters by Universal>','Labels'),
(2030,'<Permanent Self-Adhesive File Folder Labels for Typewriters, 1 1/8 x 3 1/2, White>','Labels'),
(2031,'<Personal Creations Ink Jet Cards and Labels>','Paper'),
(2032,'<Personal File Boxes with Fold-Down Carry Handle>','Storage'),
(2033,'<Personal Filing Tote with Lid, Black/Gray>','Storage'),
(2034,'<Personal Folder Holder, Ebony>','Storage'),
(2035,'<Petty Cash Envelope>','Paper'),
(2036,'<Pizazz Global Quick File>','Storage'),
(2037,'<Plantronics 81402>','Phones'),
(2038,'<Plantronics Audio 478 Stereo USB Headset>','Accessories'),
(2039,'<Plantronics Audio 995 Wireless Stereo Headset>','Accessories'),
(2040,'<Plantronics Calisto P620-M USB Wireless Speakerphone System>','Phones'),
(2041,'<Plantronics Cordless Phone Headset with In-line Volume - M214C>','Phones'),
(2042,'<Plantronics CS 50-USB - headset - Convertible, Monaural>','Phones'),
(2043,'<Plantronics CS510 - Over-the-Head monaural Wireless Headset System>','Accessories'),
(2044,'<Plantronics Encore H101 Dual Earpieces Headset>','Phones'),
(2045,'<Plantronics HL10 Handset Lifter>','Phones'),
(2046,'<Plantronics MX500i Earset>','Phones'),
(2047,'<Plantronics S12 Corded Telephone Headset System>','Accessories'),
(2048,'<Plantronics Savi W720 Multi-Device Wireless Headset System>','Accessories'),
(2049,'<Plantronics Single Ear Headset>','Machines'),
(2050,'<Plantronics Voyager Pro HD - Bluetooth Headset>','Phones'),
(2051,'<Plantronics Voyager Pro Legend>','Phones'),
(2052,'<Plastic Binding Combs>','Binders'),
(2053,'<Plymouth Boxed Rubber Bands by Plymouth>','Fasteners'),
(2054,'<Poly Designer Cover & Back>','Binders'),
(2055,'<Poly String Tie Envelopes>','Envelopes'),
(2056,'<Polycom CX300 Desktop Phone USB VoIP phone>','Phones'),
(2057,'<Polycom CX600 IP Phone VoIP phone>','Phones'),
(2058,'<Polycom SoundPoint IP 450 VoIP phone>','Phones'),
(2059,'<Polycom SoundPoint Pro SE-225 Corded phone>','Phones'),
(2060,'<Polycom SoundStation2 EX Conference phone>','Phones'),
(2061,'<Polycom VoiceStation 500 Conference phone>','Phones'),
(2062,'<Polycom VVX 310 VoIP phone>','Phones'),
(2063,'<Portable Personal File Box>','Storage'),
(2064,'<PowerGen Dual USB Car Charger>','Phones'),
(2065,'<Prang Colored Pencils>','Art'),
(2066,'<Prang Drawing Pencil Set>','Art'),
(2067,'<Prang Dustless Chalk Sticks>','Art'),
(2068,'<Premier Automatic Letter Opener>','Supplies'),
(2069,'<Premier Electric Letter Opener>','Supplies'),
(2070,'<Premier Elliptical Ring Binder, Black>','Binders'),
(2071,'<Premium Transparent Presentation Covers by GBC>','Binders'),
(2072,'<Premium Transparent Presentation Covers, No Pattern/Clear, 8 1/2" x 11">','Binders'),
(2073,'<Premium Writing Pencils, Soft, #2 by Central Association for the Blind>','Art'),
(2074,'<Pressboard Covers with Storage Hooks, 9 1/2" x 11", Light Blue>','Binders'),
(2075,'<Pressboard Data Binder, Crimson, 12" X 8 1/2">','Binders'),
(2076,'<Pressboard Data Binders by Wilson Jones>','Binders'),
(2077,'<Pressboard Hanging Data Binders for Unburst Sheets>','Binders'),
(2078,'<Presstex Flexible Ring Binders>','Binders'),
(2079,'<Prestige Round Ring Binders>','Binders'),
(2080,'<Prismacolor Color Pencil Set>','Art'),
(2081,'<Project Tote Personal File>','Storage'),
(2082,'<Pyle PMP37LED>','Phones'),
(2083,'<Pyle PRT45 Retro Home Telephone>','Phones'),
(2084,'<Quartet Omega Colored Chalk, 12/Pack>','Art'),
(2085,'<QVS USB Car Charger 2-Port 2.1Amp for iPod/iPhone/iPad/iPad 2/iPad 3>','Phones'),
(2086,'<Razer Kraken 7.1 Surround Sound Over Ear USB Gaming Headset>','Accessories'),
(2087,'<Razer Kraken PRO Over Ear PC and Music Headset>','Accessories'),
(2088,'<Razer Tiamat Over Ear 7.1 Surround Sound PC Gaming Headset>','Accessories'),
(2089,'<RCA ViSYS 25423RE1 Corded phone>','Phones'),
(2090,'<RCA ViSYS 25825 Wireless digital phone>','Phones'),
(2091,'<RCA Visys Integrated PBX 8-Line Router>','Phones'),
(2092,'<Recycled Data-Pak for Archival Bound Computer Printouts, 12-1/2 x 12-1/2 x 16>','Storage'),
(2093,'<Recycled Desk Saver Line "While You Were Out" Book, 5 1/2" X 4">','Paper'),
(2094,'<Recycled Easel Ring Binders>','Binders'),
(2095,'<Recycled Interoffice Envelopes with String and Button Closure, 10 x 13>','Envelopes'),
(2096,'<Recycled Premium Regency Composition Covers>','Binders'),
(2097,'<Recycled Pressboard Report Cover with Reinforced Top Hinge>','Binders'),
(2098,'<Recycled Steel Personal File for Hanging File Folders>','Storage'),
(2099,'<REDIFORM Incoming/Outgoing Call Register, 11" X 8 1/2", 100 Messages>','Paper'),
(2100,'<Rediform S.O.S. 1-Up Phone Message Bk, 4-1/4x3-1/16 Bk, 1 Form/Pg, 40 Messages/Bk, 3/Pk>','Paper'),
(2101,'<Rediform S.O.S. Phone Message Books>','Paper'),
(2102,'<Rediform Voice Mail Log Books>','Paper'),
(2103,'<Rediform Wirebound "Phone Memo" Message Book, 11 x 5-3/4>','Paper'),
(2104,'<Redi-Strip #10 Envelopes, 4 1/8 x 9 1/2>','Envelopes'),
(2105,'<Regeneration Desk Collection>','Furnishings'),
(2106,'<Revere Boxed Rubber Bands by Revere>','Fasteners'),
(2107,'<Ricoh - Ink Collector Unit for GX3000 Series Printers>','Machines'),
(2108,'<Riverleaf Stik-Withit Designer Note Cubes>','Paper'),
(2109,'<Riverside Furniture Oval Coffee Table, Oval End Table, End Table with Drawer>','Tables'),
(2110,'<Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish>','Bookcases'),
(2111,'<Rogers Deluxe File Chest>','Storage'),
(2112,'<Rogers Handheld Barrel Pencil Sharpener>','Art'),
(2113,'<Rogers Jumbo File, Granite>','Storage'),
(2114,'<Rogers Profile Extra Capacity Storage Tub>','Storage'),
(2115,'<Rosewill 107 Normal Keys USB Wired Standard Keyboard>','Accessories'),
(2116,'<Round Ring Binders>','Binders'),
(2117,'<Round Specialty Laser Printer Labels>','Labels'),
(2118,'<Rubber Band Ball>','Fasteners'),
(2119,'<Rubbermaid ClusterMat Chairmats, Mat Size- 66" x 60", Lip 20" x 11" -90 Degree Angle>','Furnishings'),
(2120,'<Rush Hierlooms Collection 1" Thick Stackable Bookcases>','Bookcases'),
(2121,'<SAFCO Arco Folding Chair>','Chairs'),
(2122,'<SAFCO Boltless Steel Shelving>','Storage'),
(2123,'<Safco Chair Connectors, 6/Carton>','Chairs'),
(2124,'<Safco Commercial Shelving>','Storage'),
(2125,'<SAFCO Commercial Wire Shelving, Black>','Storage'),
(2126,'<Safco Contoured Stacking Chairs>','Chairs'),
(2127,'<Safco Drafting Table>','Tables'),
(2128,'<Safco Industrial Wire Shelving>','Storage'),
(2129,'<SAFCO Mobile Desk Side File, Wire Frame>','Storage'),
(2130,'<SAFCO Optional Arm Kit for Workspace Cribbage Stacking Chair>','Chairs'),
(2131,'<SAFCO PlanMaster Boards, 60w x 37-1/2d, White Melamine>','Tables'),
(2132,'<SAFCO PlanMaster Heigh-Adjustable Drafting Table Base, 43w x 30d x 30-37h, Black>','Tables'),
(2133,'<Safco Value Mate Series Steel Bookcases, Baked Enamel Finish on Steel, Gray>','Bookcases'),
(2134,'<Safco Value Mate Steel Bookcase, Baked Enamel Finish on Steel, Black>','Bookcases'),
(2135,'<Safco Wire Cube Shelving System, For Use as 4 or 5 14" Cubes, Black>','Storage'),
(2136,'<Samsung Galaxy Mega 6.3>','Phones'),
(2137,'<Samsung Galaxy Note 2>','Phones'),
(2138,'<Samsung Galaxy Note 3>','Phones'),
(2139,'<Samsung Galaxy S III - 16GB - pebble blue (T-Mobile)>','Phones'),
(2140,'<Samsung Galaxy S4>','Phones'),
(2141,'<Samsung Galaxy S4 Mini>','Phones'),
(2142,'<Samsung HM1900 Bluetooth Headset>','Phones'),
(2143,'<Samsung Replacement EH64AVFWE Premium Headset>','Phones'),
(2144,'<Samsung Rugby III>','Phones'),
(2145,'<SanDisk Cruzer 32 GB USB Flash Drive>','Accessories'),
(2146,'<SanDisk Cruzer 64 GB USB Flash Drive>','Accessories'),
(2147,'<SanDisk Ultra 16 GB MicroSDHC Class 10 Memory Card>','Accessories'),
(2148,'<SanDisk Ultra 32 GB MicroSDHC Class 10 Memory Card>','Accessories'),
(2149,'<SanDisk Ultra 64 GB MicroSDHC Class 10 Memory Card>','Accessories'),
(2150,'<Sanford 52201 APSCO Electric Pencil Sharpener>','Art'),
(2151,'<Sanford Colorific Colored Pencils, 12/Box>','Art'),
(2152,'<Sanford Colorific Eraseable Coloring Pencils, 12 Count>','Art'),
(2153,'<Sanford EarthWrite Recycled Pencils, Medium Soft, #2>','Art'),
(2154,'<SANFORD Liquid Accent Tank-Style Highlighters>','Art'),
(2155,'<SANFORD Major Accent Highlighters>','Art'),
(2156,'<Sanyo 2.5 Cubic Foot Mid-Size Office Refrigerators>','Appliances'),
(2157,'<Sanyo Counter Height Refrigerator with Crisper, 3.6 Cubic Foot, Stainless Steel/Black>','Appliances'),
(2158,'<Satellite Sectional Post Binders>','Binders'),
(2159,'<Sauder Barrister Bookcases>','Bookcases'),
(2160,'<Sauder Camden County Barrister Bookcase, Planked Cherry Finish>','Bookcases'),
(2161,'<Sauder Camden County Collection Libraries, Planked Cherry Finish>','Bookcases'),
(2162,'<Sauder Camden County Collection Library>','Bookcases'),
(2163,'<Sauder Facets Collection Library, Sky Alder Finish>','Bookcases'),
(2164,'<Sauder Facets Collection Locker/File Cabinet, Sky Alder Finish>','Storage'),
(2165,'<Sauder Forest Hills Library with Doors, Woodland Oak Finish>','Bookcases'),
(2166,'<Sauder Forest Hills Library, Woodland Oak Finish>','Bookcases'),
(2167,'<Sauder Inglewood Library Bookcases>','Bookcases'),
(2168,'<Sauder Mission Library with Doors, Fruitwood Finish>','Bookcases'),
(2169,'<Security-Tint Envelopes>','Envelopes'),
(2170,'<Seidio BD2-HK3IPH5-BK DILEX Case and Holster Combo for Apple iPhone 5/5s - Black>','Phones'),
(2171,'<Self-Adhesive Address Labels for Typewriters by Universal>','Labels'),
(2172,'<Self-Adhesive Removable Labels>','Labels'),
(2173,'<Self-Adhesive Ring Binder Labels>','Binders'),
(2174,'<Sensible Storage WireTech Storage Systems>','Storage'),
(2175,'<Serrated Blade or Curved Handle Hand Letter Openers>','Supplies'),
(2176,'<Seth Thomas 12" Clock w/ Goldtone Case>','Furnishings'),
(2177,'<Seth Thomas 13 1/2" Wall Clock>','Furnishings'),
(2178,'<Seth Thomas 14" Day/Date Wall Clock>','Furnishings'),
(2179,'<Seth Thomas 16" Steel Case Clock>','Furnishings'),
(2180,'<Seth Thomas 8 1/2" Cubicle Clock>','Furnishings'),
(2181,'<Sharp 1540cs Digital Laser Copier>','Copiers'),
(2182,'<Sharp AL-1530CS Digital Copier>','Copiers'),
(2183,'<Shocksock Galaxy S4 Armband>','Phones'),
(2184,'<ShoreTel ShorePhone IP 230 VoIP phone>','Phones'),
(2185,'<SimpliFile Personal File, Black Granite, 15w x 6-15/16d x 11-1/4h>','Storage'),
(2186,'<Situations Contoured Folding Chairs, 4/Set>','Chairs'),
(2187,'<SlimView Poly Binder, 3/8">','Binders'),
(2188,'<SmartStand Mobile Device Holder, Assorted Colors>','Phones'),
(2189,'<Smead Alpha-Z Color-Coded Name Labels First Letter Starter Set>','Labels'),
(2190,'<Smead Alpha-Z Color-Coded Second Alphabetical Labels and Starter Set>','Labels'),
(2191,'<Snap-A-Way Black Print Carbonless Ruled Speed Letter, Triplicate>','Paper'),
(2192,'<Socket Bluetooth Cordless Hand Scanner (CHS)>','Machines'),
(2193,'<Sony 16GB Class 10 Micro SDHC R40 Memory Card>','Accessories'),
(2194,'<Sony 32GB Class 10 Micro SDHC R40 Memory Card>','Accessories'),
(2195,'<Sony 64GB Class 10 Micro SDHC R40 Memory Card>','Accessories'),
(2196,'<Sony Micro Vault Click 16 GB USB 2.0 Flash Drive>','Accessories'),
(2197,'<Sony Micro Vault Click 4 GB USB 2.0 Flash Drive>','Accessories'),
(2198,'<Sony Micro Vault Click 8 GB USB 2.0 Flash Drive>','Accessories'),
(2199,'<Sortfiler Multipurpose Personal File Organizer, Black>','Storage'),
(2200,'<Southworth 100% Résumé Paper, 24lb.>','Paper'),
(2201,'<Southworth 25% Cotton Antique Laid Paper & Envelopes>','Paper'),
(2202,'<Southworth 25% Cotton Linen-Finish Paper & Envelopes>','Paper'),
(2203,'<Southworth 25% Cotton Premium Laser Paper and Envelopes>','Paper'),
(2204,'<Southworth Parchment Paper & Envelopes>','Paper'),
(2205,'<Southworth Structures Collection>','Paper'),
(2206,'<Space Solutions Commercial Steel Shelving>','Storage'),
(2207,'<Space Solutions HD Industrial Steel Shelving.>','Storage'),
(2208,'<SpineVue Locking Slant-D Ring Binders by Cardinal>','Binders'),
(2209,'<Spiral Phone Message Books with Labels by Adams>','Paper'),
(2210,'<Square Credit Card Reader>','Phones'),
(2211,'<Square Credit Card Reader, 4 1/2" x 4 1/2" x 1", White>','Phones'),
(2212,'<Square Ring Data Binders, Rigid 75 Pt. Covers, 11" x 14-7/8">','Binders'),
(2213,'<Stackable Trays>','Furnishings'),
(2214,'<Stacking Trays by OIC>','Furnishings'),
(2215,'<Standard Line “While You Were Out” Hardbound Telephone Message Book>','Paper'),
(2216,'<Standard Rollaway File with Lock>','Storage'),
(2217,'<Stanley Contemporary Battery Pencil Sharpeners>','Art'),
(2218,'<Staples>','Fasteners'),
(2219,'<Star Micronics TSP800 TSP847IIU Receipt Printer>','Machines'),
(2220,'<StarTech.com 10/100 VDSL2 Ethernet Extender Kit>','Machines'),
(2221,'<Sterilite Officeware Hinged File Box>','Storage'),
(2222,'<Sterilite Show Offs Storage Containers>','Storage'),
(2223,'<Sterling Rubber Bands by Alliance>','Fasteners'),
(2224,'<Stiletto Hand Letter Openers>','Supplies'),
(2225,'<Stockwell Push Pins>','Fasteners'),
(2226,'<Storex Dura Pro Binders>','Binders'),
(2227,'<Storex Flexible Poly Binders with Double Pockets>','Binders'),
(2228,'<Strathmore #10 Envelopes, Ultimate White>','Envelopes'),
(2229,'<Strathmore Photo Frame Cards>','Paper'),
(2230,'<Strathmore Photo Mount Cards>','Paper'),
(2231,'<Stur-D-Stor Shelving, Vertical 5-Shelf: 72"H x 36"W x 18 1/2"D>','Storage'),
(2232,'<Super Bands, 12/Pack>','Fasteners'),
(2233,'<Super Decoflex Portable Personal File>','Storage'),
(2234,'<Surelock Post Binders>','Binders'),
(2235,'<Swingline SM12-08 MicroCut Jam Free Shredder>','Machines'),
(2236,'<Telephone Message Books with Fax/Mobile Section, 5 1/2" x 3 3/16">','Paper'),
(2237,'<Tenex "The Solids" Textured Chair Mats>','Furnishings'),
(2238,'<Tenex 46" x 60" Computer Anti-Static Chairmat, Rectangular Shaped>','Furnishings'),
(2239,'<Tenex B1-RE Series Chair Mats for Low Pile Carpets>','Furnishings'),
(2240,'<Tenex Carpeted, Granite-Look or Clear Contemporary Contour Shape Chair Mats>','Furnishings'),
(2241,'<Tenex Chairmats For Use With Carpeted Floors>','Furnishings'),
(2242,'<Tenex Chairmats For Use with Hard Floors>','Furnishings'),
(2243,'<Tenex Contemporary Contur Chairmats for Low and Medium Pile Carpet, Computer, 39" x 49">','Furnishings'),
(2244,'<Tenex File Box, Personal Filing Tote with Lid, Black>','Storage'),
(2245,'<Tenex Personal Filing Tote With Secure Closure Lid, Black/Frost>','Storage'),
(2246,'<Tenex Personal Project File with Scoop Front Design, Black>','Storage'),
(2247,'<Tenex Traditional Chairmats for Hard Floors, Average Lip, 36" x 48">','Furnishings'),
(2248,'<Tenex Traditional Chairmats for Medium Pile Carpet, Standard Lip, 36" x 48">','Furnishings'),
(2249,'<Tenex V2T-RE Standard Weight Series Chair Mat, 45" x 53", Lip 25" x 12">','Furnishings'),
(2250,'<Tennsco 16-Compartment Lockers with Coat Rack>','Storage'),
(2251,'<Tennsco 6- and 18-Compartment Lockers>','Storage'),
(2252,'<Tennsco Commercial Shelving>','Storage'),
(2253,'<Tennsco Double-Tier Lockers>','Storage'),
(2254,'<Tennsco Industrial Shelving>','Storage'),
(2255,'<Tennsco Lockers, Gray>','Storage'),
(2256,'<Tennsco Regal Shelving Units>','Storage'),
(2257,'<Tennsco Single-Tier Lockers>','Storage'),
(2258,'<Tennsco Snap-Together Open Shelving Units, Starter Sets and Add-On Units>','Storage'),
(2259,'<Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24" Deep, Sand>','Storage'),
(2260,'<Tensor Brushed Steel Torchiere Floor Lamp>','Furnishings'),
(2261,'<Tensor Computer Mounted Lamp>','Furnishings'),
(2262,'<Texas Instrument TI-15 Fraction Calculator>','Machines'),
(2263,'<Texas Instruments TI-34 Scientific Calculator>','Machines'),
(2264,'<Things To Do Today Pad>','Paper'),
(2265,'<Things To Do Today Spiral Book>','Paper'),
(2266,'<TOPS "Important Message" Pads, Canary, 4-1/4 x 5-1/2, 50 Sheets per Pad>','Paper'),
(2267,'<TOPS 4 x 6 Fluorescent Color Memo Sheets, 500 Sheets per Pack>','Paper'),
(2268,'<TOPS Carbonless Receipt Book, Four 2-3/4 x 7-1/4 Money Receipts per Page>','Paper'),
(2269,'<Tops Green Bar Computer Printout Paper>','Paper'),
(2270,'<TOPS Money Receipt Book, Consecutively Numbered in Red,>','Paper'),
(2271,'<Tops White Computer Printout Paper>','Paper'),
(2272,'<Tops Wirebound Message Log Books>','Paper'),
(2273,'<Toshiba IPT2010-SD IP Telephone>','Phones'),
(2274,'<Trav-L-File Heavy-Duty Shuttle II, Black>','Storage'),
(2275,'<TRENDnet 56K USB 2.0 Phone, Internet and Fax Modem>','Accessories'),
(2276,'<Trimflex Flexible Post Binders>','Binders'),
(2277,'<Tripp Lite TLP810NET Broadband Surge for Modem/Fax>','Appliances'),
(2278,'<Tuff Stuff Recycled Round Ring Binders>','Binders'),
(2279,'<Tuf-Vin Binders>','Binders'),
(2280,'<Turquoise Lead Holder with Pocket Clip>','Art'),
(2281,'<Tyvek  Top-Opening Peel & Seel Envelopes, Plain White>','Envelopes'),
(2282,'<Tyvek Interoffice Envelopes, 9 1/2" x 12 1/2", 100/Box>','Envelopes'),
(2283,'<Tyvek Side-Opening Peel & Seel Expanding Envelopes>','Envelopes'),
(2284,'<Ultra Door Pull Handle>','Furnishings'),
(2285,'<Ultra Door Push Plate>','Furnishings'),
(2286,'<UniKeep View Case Binders>','Binders'),
(2287,'<Universal Premium White Copier/Laser Paper (20Lb. and 87 Bright)>','Paper'),
(2288,'<Universal Recycled Hanging Pressboard Report Binders, Letter Size>','Binders'),
(2289,'<Universal Ultra Bright White Copier/Laser Paper, 8 1/2" x 11", Ream>','Paper'),
(2290,'<Unpadded Memo Slips>','Paper'),
(2291,'<VariCap6 Expandable Binder>','Binders'),
(2292,'<Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 10/Pack>','Accessories'),
(2293,'<Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 3/Pack>','Accessories'),
(2294,'<Verbatim Slim CD and DVD Storage Cases, 50/Pack>','Accessories'),
(2295,'<Vinyl Coated Wire Paper Clips in Organizer Box, 800/Box>','Fasteners'),
(2296,'<Vinyl Sectional Post Binders>','Binders'),
(2297,'<Vtech AT&T CL2940 Corded Speakerphone, Black>','Machines'),
(2298,'<Vtech CS6719>','Phones'),
(2299,'<VTech DS6151>','Phones'),
(2300,'<Wausau Papers Astrobrights Colored Envelopes>','Envelopes'),
(2301,'<WD My Passport Ultra 1TB Portable External Hard Drive>','Accessories'),
(2302,'<WD My Passport Ultra 2TB Portable External Hard Drive>','Accessories'),
(2303,'<WD My Passport Ultra 500GB Portable External Hard Drive>','Accessories'),
(2304,'<Westinghouse Clip-On Gooseneck Lamps>','Furnishings'),
(2305,'<Westinghouse Floor Lamp with Metal Mesh Shade, Black>','Furnishings'),
(2306,'<Westinghouse Mesh Shade Clip-On Gooseneck Lamp, Black>','Furnishings'),
(2307,'<Weyerhaeuser First Choice Laser/Copy Paper (20Lb. and 88 Bright)>','Paper'),
(2308,'<While You Were Out Pads, 50 per Pad, 4 x 5 1/4, Green Cycle>','Paper'),
(2309,'<White Business Envelopes with Contemporary Seam, Recycled White Business Envelopes>','Envelopes'),
(2310,'<White Computer Printout Paper by Universal>','Paper'),
(2311,'<White Dual Perf Computer Printout Paper, 2700 Sheets, 1 Part, Heavyweight, 20 lbs., 14 7/8 x 11>','Paper'),
(2312,'<White Envelopes, White Envelopes with Clear Poly Window>','Envelopes'),
(2313,'<White GlueTop Scratch Pads>','Paper'),
(2314,'<Wi-Ex zBoost YX540 Cellular Phone Signal Booster>','Phones'),
(2315,'<Wilson Electronics DB Pro Signal Booster>','Phones'),
(2316,'<Wilson Jones 1" Hanging DublLock Ring Binders>','Binders'),
(2317,'<Wilson Jones 14 Line Acrylic Coated Pressboard Data Binders>','Binders'),
(2318,'<Wilson Jones Active Use Binders>','Binders'),
(2319,'<Wilson Jones Century Plastic Molded Ring Binders>','Binders'),
(2320,'<Wilson Jones Clip & Carry Folder Binder Tool for Ring Binders, Clear>','Binders'),
(2321,'<Wilson Jones Custom Binder Spines & Labels>','Binders'),
(2322,'<Wilson Jones data.warehouse D-Ring Binders with DublLock>','Binders'),
(2323,'<Wilson Jones DublLock D-Ring Binders>','Binders'),
(2324,'<Wilson Jones Easy Flow II Sheet Lifters>','Binders'),
(2325,'<Wilson Jones Elliptical Ring 3 1/2" Capacity Binders, 800 sheets>','Binders'),
(2326,'<Wilson Jones Four-Pocket Poly Binders>','Binders'),
(2327,'<Wilson Jones Hanging View Binder, White, 1">','Binders'),
(2328,'<Wilson Jones Heavy-Duty Casebound Ring Binders with Metal Hinges>','Binders'),
(2329,'<Wilson Jones Impact Binders>','Binders'),
(2330,'<Wilson Jones International Size A4 Ring Binders>','Binders'),
(2331,'<Wilson Jones Leather-Like Binders with DublLock Round Rings>','Binders'),
(2332,'<Wilson Jones Ledger-Size, Piano-Hinge Binder, 2", Blue>','Binders'),
(2333,'<Wilson Jones Legal Size Ring Binders>','Binders'),
(2334,'<Wilson Jones Standard D-Ring Binders>','Binders'),
(2335,'<Wilson Jones Turn Tabs Binder Tool for Ring Binders>','Binders'),
(2336,'<Wilson SignalBoost 841262 DB PRO Amplifier Kit>','Phones'),
(2337,'<Wirebound Four 2-3/4 x 5 Forms per Page, 400 Sets per Book>','Paper'),
(2338,'<Wirebound Message Book, 4 per Page>','Paper'),
(2339,'<Wirebound Message Books, 2 7/8" x 5", 3 Forms per Page>','Paper'),
(2340,'<Wirebound Message Books, 5-1/2 x 4 Forms, 2 or 4 Forms per Page>','Paper'),
(2341,'<Wirebound Message Books, Four 2 3/4 x 5 Forms per Page, 200 Sets per Book>','Paper'),
(2342,'<Wirebound Message Books, Four 2 3/4 x 5 White Forms per Page>','Paper'),
(2343,'<Wirebound Message Books, Four 2 3/4" x 5" Forms per Page, 600 Sets per Book>','Paper'),
(2344,'<Wirebound Message Books, Two 4 1/4" x 5" Forms per Page>','Paper'),
(2345,'<Wirebound Message Forms, Four 2 3/4 x 5 Forms per Page, Pink Paper>','Paper'),
(2346,'<Wirebound Service Call Books, 5 1/2" x 4">','Paper'),
(2347,'<Wireless Extenders zBoost YX545 SOHO Signal Booster>','Phones'),
(2348,'<Woodgrain Magazine Files by Perma>','Storage'),
(2349,'<Xerox 1880>','Paper'),
(2350,'<Xerox 1881>','Paper'),
(2351,'<Xerox 1882>','Paper'),
(2352,'<Xerox 1883>','Paper'),
(2353,'<Xerox 1884>','Paper'),
(2354,'<Xerox 1885>','Paper'),
(2355,'<Xerox 1886>','Paper'),
(2356,'<Xerox 1887>','Paper'),
(2357,'<Xerox 1888>','Paper'),
(2358,'<Xerox 189>','Paper'),
(2359,'<Xerox 1891>','Paper'),
(2360,'<Xerox 1892>','Paper'),
(2361,'<Xerox 1893>','Paper'),
(2362,'<Xerox 1894>','Paper'),
(2363,'<Xerox 1895>','Paper'),
(2364,'<Xerox 1896>','Paper'),
(2365,'<Xerox 1897>','Paper'),
(2366,'<Xerox 1898>','Paper'),
(2367,'<Xerox 1899>','Paper'),
(2368,'<Xerox 19>','Paper'),
(2369,'<Xerox 190>','Paper'),
(2370,'<Xerox 1900>','Paper'),
(2371,'<Xerox 1903>','Paper'),
(2372,'<Xerox 1905>','Paper'),
(2373,'<Xerox 1907>','Paper'),
(2374,'<Xerox 1908>','Paper'),
(2375,'<Xerox 1909>','Paper'),
(2376,'<Xerox 191>','Paper'),
(2377,'<Xerox 1911>','Paper'),
(2378,'<Xerox 1912>','Paper'),
(2379,'<Xerox 1913>','Paper'),
(2380,'<Xerox 1914>','Paper'),
(2381,'<Xerox 1915>','Paper'),
(2382,'<Xerox 1916>','Paper'),
(2383,'<Xerox 1917>','Paper'),
(2384,'<Xerox 1919>','Paper'),
(2385,'<Xerox 192>','Paper'),
(2386,'<Xerox 1920>','Paper'),
(2387,'<Xerox 1922>','Paper'),
(2388,'<Xerox 1923>','Paper'),
(2389,'<Xerox 1924>','Paper'),
(2390,'<Xerox 1925>','Paper'),
(2391,'<Xerox 1927>','Paper'),
(2392,'<Xerox 1928>','Paper'),
(2393,'<Xerox 1929>','Paper'),
(2394,'<Xerox 193>','Paper'),
(2395,'<Xerox 1930>','Paper'),
(2396,'<Xerox 1931>','Paper'),
(2397,'<Xerox 1932>','Paper'),
(2398,'<Xerox 1933>','Paper'),
(2399,'<Xerox 1934>','Paper'),
(2400,'<Xerox 1937>','Paper'),
(2401,'<Xerox 1939>','Paper'),
(2402,'<Xerox 194>','Paper'),
(2403,'<Xerox 1940>','Paper'),
(2404,'<Xerox 1941>','Paper'),
(2405,'<Xerox 1942>','Paper'),
(2406,'<Xerox 1943>','Paper'),
(2407,'<Xerox 1944>','Paper'),
(2408,'<Xerox 1945>','Paper'),
(2409,'<Xerox 1946>','Paper'),
(2410,'<Xerox 1947>','Paper'),
(2411,'<Xerox 1949>','Paper'),
(2412,'<Xerox 195>','Paper'),
(2413,'<Xerox 1951>','Paper'),
(2414,'<Xerox 1952>','Paper'),
(2415,'<Xerox 1953>','Paper'),
(2416,'<Xerox 1954>','Paper'),
(2417,'<Xerox 1959>','Paper'),
(2418,'<Xerox 196>','Paper'),
(2419,'<Xerox 1960>','Paper'),
(2420,'<Xerox 1962>','Paper'),
(2421,'<Xerox 1964>','Paper'),
(2422,'<Xerox 1965>','Paper'),
(2423,'<Xerox 1966>','Paper'),
(2424,'<Xerox 1967>','Paper'),
(2425,'<Xerox 1968>','Paper'),
(2426,'<Xerox 1970>','Paper'),
(2427,'<Xerox 1971>','Paper'),
(2428,'<Xerox 1972>','Paper'),
(2429,'<Xerox 1973>','Paper'),
(2430,'<Xerox 1974>','Paper'),
(2431,'<Xerox 1975>','Paper'),
(2432,'<Xerox 1976>','Paper'),
(2433,'<Xerox 1977>','Paper'),
(2434,'<Xerox 1978>','Paper'),
(2435,'<Xerox 1979>','Paper'),
(2436,'<Xerox 1981>','Paper'),
(2437,'<Xerox 1982>','Paper'),
(2438,'<Xerox 1983>','Paper'),
(2439,'<Xerox 1984>','Paper'),
(2440,'<Xerox 1986>','Paper'),
(2441,'<Xerox 1987>','Paper'),
(2442,'<Xerox 1988>','Paper'),
(2443,'<Xerox 1991>','Paper'),
(2444,'<Xerox 1992>','Paper'),
(2445,'<Xerox 1995>','Paper'),
(2446,'<Xerox 1996>','Paper'),
(2447,'<Xerox 1997>','Paper'),
(2448,'<Xerox 1999>','Paper'),
(2449,'<Xerox 2>','Paper'),
(2450,'<Xerox 20>','Paper'),
(2451,'<Xerox 200>','Paper'),
(2452,'<Xerox 2000>','Paper'),
(2453,'<Xerox 201>','Paper'),
(2454,'<Xerox 202>','Paper'),
(2455,'<Xerox 203>','Paper'),
(2456,'<Xerox 204>','Paper'),
(2457,'<Xerox 206>','Paper'),
(2458,'<Xerox 209>','Paper'),
(2459,'<Xerox 21>','Paper'),
(2460,'<Xerox 210>','Paper'),
(2461,'<Xerox 211>','Paper'),
(2462,'<Xerox 212>','Paper'),
(2463,'<Xerox 213>','Paper'),
(2464,'<Xerox 214>','Paper'),
(2465,'<Xerox 215>','Paper'),
(2466,'<Xerox 216>','Paper'),
(2467,'<Xerox 217>','Paper'),
(2468,'<Xerox 218>','Paper'),
(2469,'<Xerox 219>','Paper'),
(2470,'<Xerox 22>','Paper'),
(2471,'<Xerox 220>','Paper'),
(2472,'<Xerox 221>','Paper'),
(2473,'<Xerox 222>','Paper'),
(2474,'<Xerox 223>','Paper'),
(2475,'<Xerox 225>','Paper'),
(2476,'<Xerox 226>','Paper'),
(2477,'<Xerox 227>','Paper'),
(2478,'<Xerox 228>','Paper'),
(2479,'<Xerox 229>','Paper'),
(2480,'<Xerox 23>','Paper'),
(2481,'<Xerox 230>','Paper'),
(2482,'<Xerox 231>','Paper'),
(2483,'<Xerox 232>','Paper'),
(2484,'<Xerox 4200 Series MultiUse Premium Copy Paper (20Lb. and 84 Bright)>','Paper'),
(2485,'<Xerox Blank Computer Paper>','Paper'),
(2486,'<Xerox Color Copier Paper, 11" x 17", Ream>','Paper'),
(2487,'<X-Rack File for Hanging Folders>','Storage'),
(2488,'<XtraLife ClearVue Slant-D Ring Binder, White, 3">','Binders'),
(2489,'<XtraLife ClearVue Slant-D Ring Binders by Cardinal>','Binders'),
(2490,'<Zebra GK420t Direct Thermal/Thermal Transfer Printer>','Machines'),
(2491,'<Zebra GX420t Direct Thermal/Thermal Transfer Printer>','Machines'),
(2492,'<Zebra Zazzle Fluorescent Highlighters>','Art'),
(2493,'<Zipper Ring Binder Pockets>','Binders')